if vim.g.vscode then
  return
end

-- orgmode
require("orgmode").setup({
  org_agenda_files = "~/notes/**/*",
  org_default_notes_file = "~/notes/refile.org",
  org_startup_folded = "showeverything",
  mappings = {
    disable_all = false,
    global = {
      org_agenda = "<leader>oa",
      org_capture = "<leader>oc",
    },
    org = {
      org_refile = "<leader>or",
      org_timestamp_up_day = "<S-UP>",
      org_timestamp_down_day = "<S-DOWN>",
      org_timestamp_up = "<C-a>",

      org_timestamp_down = "<C-x>",
      org_change_date = "cid",
      --org_priority = '<leader>o,',
      org_priority_up = "ciR",
      org_priority_down = "cir",
      org_todo = "cit",
      org_todo_prev = "ciT",
      --org_toggle_checkbox = '<C-Space>',
      --org_toggle_heading = '<leader>o*',
      org_open_at_point = "<leader>of",
      --org_edit_special = [[<leader>o']],
      org_cycle = false,
      org_global_cycle = false,
      org_archive_subtree = "<leader>o$",
      org_set_tags_command = "<leader>ot",
      org_toggle_archive_tag = "<leader>oA",
      org_do_promote = "<<",
      org_do_demote = ">>",
      org_promote_subtree = "<s",
      org_demote_subtree = ">s",
      org_meta_return = "<leader><CR>", -- Add headling, item or row
      org_insert_heading_respect_content = "<leader>oih", -- Add new headling after current heading block with same level
      org_insert_todo_heading = "<leader>oiT", -- Add new todo headling right after current heading with same level
      org_insert_todo_heading_respect_content = "<leader>oit", -- Add new todo headling after current heading block on same level
      org_move_subtree_up = "<leader>oK",
      org_move_subtree_down = "<leader>oJ",
      org_export = "<leader>oe",
      org_next_visible_heading = "}",
      org_previous_visible_heading = "{",
      org_forward_heading_same_level = "]]",
      org_backward_heading_same_level = "[[",
      outline_up_heading = "g{",
      org_deadline = "<leader>oid",
      org_schedule = "<leader>ois",
      org_time_stamp = "<leader>oi.",
      org_time_stamp_inactive = "<leader>oi,",
      org_clock_in = "<leader>oxi",
      org_clock_out = "<leader>oxo",
      org_clock_cancel = "<leader>oxq",
      org_clock_goto = "<leader>oxj",
      org_set_effort = "<leader>oxe",
      org_show_help = "g?",
    },
    agenda = {
      org_agenda_later = "f",
      org_agenda_earlier = "b",
      org_agenda_goto_today = ".",
      org_agenda_day_view = "vd",
      org_agenda_week_view = "vw",
      org_agenda_month_view = "vm",
      org_agenda_year_view = "vy",
      org_agenda_quit = "q",
      org_agenda_switch_to = "<CR>",
      org_agenda_goto = { "<TAB>" },
      org_agenda_goto_date = "J",
      org_agenda_redo = "r",
      org_agenda_todo = "t",
      org_agenda_clock_goto = "<leader>oxj",
      org_agenda_set_effort = "<leader>oxe",
      org_agenda_clock_in = "I",
      org_agenda_clock_out = "O",
      org_agenda_clock_cancel = "X",
      org_agenda_clockreport_mode = "R",
      org_agenda_priority = "<leader>o,",
      org_agenda_priority_up = "+",
      org_agenda_priority_down = "-",
      org_agenda_toggle_archive_tag = "<leader>oA",
      org_agenda_set_tags = "<leader>ot",
      org_agenda_deadline = "<leader>oid",
      org_agenda_schedule = "<leader>ois",
      org_agenda_filter = "/",
      org_agenda_show_help = "g?",
    },
    edit_src = {
      org_edit_src_abort = "<leader>ok",
      org_edit_src_save = "<leader>ow",
      org_edit_src_show_help = "g?",
    },
  },
})
