vpn:
    pk: ENC[AES256_GCM,data:FgFTNSSrR5n+MSoU6OH/JS2vT4nJdFdvPVNroiA7gBIrt3YBU9fsOfA2Sy0=,iv:JHqlUK+8m4TV1wbki4pxGfpdRS6IZ48XcmAgcHVQha0=,tag:1UX55M5Zy8IcPEy86zzFgA==,type:str]
syncthing:
    key: ENC[AES256_GCM,data:+Wow+ZWLZ5Gs63qfEynm5q3HmjYo2LMVtBOV9ff5EOT/h2Ux+ix+Q+TQ9ozd4m33iJZbF0o7Ub/yWD2SLXTiLCnWm2ZWS6bSIg0wnKXXaIR2grArVCJCjOYPRryVREMOcGG585IedkW+On1Ufuy2NRK6fGj1pfY=,iv:96Z8zXHgDUEObcK5GUzvhg0Ts1NXbLw+NP8Raxc5Qoo=,tag:oYBGUuHp/CcteAkpoFry6w==,type:str]
kdeconnect:
    key: ENC[AES256_GCM,data:1qSUrza5o+zNBAHdegGW0WzGrvzDklZq6jn3dn33Po8pnO4WFKlnVteXcLHS0ulHy5KHL7VcRcTedKTYOmEICTn1VcZ81igTDv569FnlwCYxkbCbAa/VIXRFuwrUEm7wELqCJqoJZm/RDP8CDhjlk3XuyhkGXD3zwmfaSCgt5IAo3A48h3/u8O4vpZI6swD/VyNvVNV4F1l/IcPRBL0pSOYizl0EvuZbeT7F45+zZSOe3HMvNqGoQCV0/cU90OQgDtgSecinahs0+t79H3CO9eXsGj78XY6Q8FNq0vFRmN6G8Am/mtrr/LFZSOLf+2AijA==,iv:Pdx6AG7JnkN7u57EiQBqyVxOt8jO7Zf8LpAdkXDGg5w=,tag:N/hajWKG+UxgxYdSHbdYgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IE8rSkh6ZEY3
            L2p2c1pGcWFPUW05SUx1cHdML0tyWmpnRGIyYjF5VnU0RjZEODV4V2NzaGdicVpk
            Tzh5cmlDbFdQeWt3MjV6UGk4aXJTYkxTbnZONlpYRlZWYXpaUno4RzBYRlUwZWJW
            OUUxVm1aUnZKUThmTXVvNi9uTi9XdXVad0dlanZEaDlMK0VrWjlMdkoydVFFNXpw
            dFVNV2l1dzRvS3l6c25jTFlJSjFlMGpjUkJJLzB4VzZVS0IwK0szNlVtY3FQVXhQ
            U01JdVJVdUNEbVRzaEtqb2s1RVhTM0t6MWhvZ1hxRUFWN3FWdnBHMWR2ZmlQOUNw
            OElsZHRVZWc2K1AvNllpZWxnaTN4aXRKSjlmSDVJTHVFSG5IUVZ1V0gxSVVoZ0RU
            cU1mUmtJbXNTenJMTkJzQ0pId1ErSEE1RjNkOGNGVmtHS0FtNm91eDFBNERrdkxu
            U0JaVWdra3gzWm4vRmpDaUY2SVk2VW1mQlIyTWxNMzliREM1S3h4cHZWSjRlcHdF
            Vzh6eFdELzB4cmY4bHpXU1ZieUViWWJOZld2VTZWWjlFNkpjakxBMlBHVTZSSTg5
            V0U0dkIwaXNtYnJpRjhsSE1CbWt5aDdmSzdMc2F5UEJ5R3VvS2lldlhiODkyYk1N
            VHg0MDRlaTRDRlpSbzRvRHU0a3lNclZpNVF5aWF6QUptM3lxVWdObDZCR2ZEM2Vy
            NzNZajRRODkxK1ZXY1ZWbWxzdzE4V3FqOHVWdG1IcjBmZFlWQU94dEdRZ3A0bVBs
            dkhBUXdiRGt6VlUwS1BramFBa0o4L24yL0wxNGl4VVB3S1pCckNkeXdVZUgvT0sy
            ZEl2ZVJtczliSGVzbGNheWQrS0VTbnBCQmlrRXd1VURJQTNyTHZ3L3F4ZXhkNEMz
            c051K0tlciszczRZYmM4SU9PSWsweVAxN1ZMeVpURlRvTk52UDRpU2RSaURJWWEr
            R09kVFpPazRrdmtUWmJEM3JpaFNLUk05QUdnRUVkWE5tRzc0ekFlRm5vVHhrNXdk
            Zlh6b2hDVVhWeU9iQmZ1YjhLKzc0bXNoU2FJRnZuUjhWbUlaZVVSMlppNjM2UTRO
            NUVxb2ZzVmp2Qm5DSFl2ZUJmVnZiamk3TWJJaDh4eFdVejR4bEc4VkovVnFvMmd6
            SmhIcS9JSklJTnhjbU9PTmNCVTBTeU13R0xUUzRxZy8zeFJuTit1WHY5L1hCS0Ez
            S1BVQ254b3JwVU8rOWVkaWYrNG5aYitSMnl2TEUyNkxvS3J1bkpkaHRNUzRVQmw2
            RGx6Q3M5YUplUlo2c3FhSnhYdE1PbEIzYXdBZS9ZRDluTWZJVmVvMEVab0h2a3R6
            U1dUZWJURDlDeXh3aVlEdHJIMjZPeUo4dG1DUFY2QTh3eVFNR2habFhOdHJEdFBX
            U1NVa1dJWTlXK1loVXYwcWdHcGxpdlhweHZSMXlQVFNOSThZek4rcTJiaE80c2V0
            RVAwV2NzL1U5M0FHNjVMbmlmYTI5alpjY3BQTEw0L3YzbjlDb01jbTN3S3N3c2J6
            Rnh5K2IxYTlHYytiZVVQN29vTDVMd2IyaFA5Q25xbmJxRVQ5UGsvZUNyZnMzRHRl
            MEJTdTlRL1hBaWgwakZGb0ZUZmlxb2N4UHcvK3Uzc09yTUgyMktwS2JHZVUxWDR6
            Q0VMQnpYN1dTSURITVF5elR2V3pUR0kyRi9xWmpaaVF4Q24weEp5M3E1bWxjNmY4
            UE9ONVRWOUtHZWI0amk0MjAyOXRjTjdCY29mMnRJMGJ5ZnQrTThqTnp5TEZLaDVB
            NThOekhJUE9taEtQR01YSk5zNzVVZHh4WVIyYWpmUVJJdnFFc29BMlNvWUpXRllJ
            eG1mZ0ROZ0liT0J0YjBEVHc1OGZ5azUyU3EwcU8wYlg4b3k4TWgrUWV3NjFaWHQ1
            VnFhVW1qMWluZ3p0djdqTXRvb3ljREdONDFOOUg1UmphSU1LVkhiamZsRTdaZwpJ
            TXFlTllvbGNZQ2RGa1NVd0c3N2t0Qk51SCtsWS92MWtMeTUvU2s5dlJjCi0tLSBj
            dDRsRGtqdFQ3OEh3Y0lKaVhZWit0SU1Obm5RY1BWaFRiWlc3bmFLZTRZCslXnfab
            2RO/+LVV/2ki3nyQc4J4Oy52ZVJCL3MhUtCNLal5nta1rEicXU2CX4MyNVrJPlp8
            n1em7OqUr1r+y/0=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq15zkgrl6kqmch899ejsehzdqvyudyz33uq65njscappkvfqm4tqermjgud0rddvq4rpryr5r5jx35c844fsr7245k72jtd755tdqmt6jgv84pt2g6kz0plkugknvr6s84x5f9s906qdlrwsmjveyu3egvv8mxhvfxhxtpw9qqvwmt7uf8jtk6sq7xgk49yau46ufr8qf2q05ycjyxvf57hpsrvlr2ylj3jg6j59uknsc8xsexvfrmwaar02w43wdfdwjz6x2pklycp5fr4za4zm3s0scyz5u00nrpgrr2sqwqn03xusjredazgsy5qrwjgy6jk06rhxp7cxs86w4h0gqtpewmes8yk5lhfjdajwucv8tr2nh049vtas8r5yplykjt96u2pm405wmuk3zrkgc2lwm5jnq222ur5vc3aqlee6qpdkdne69tcr7jv4j9vfwppzqnzwanane3qmd2dtvgc9nxugxz0z4m0mexrwtmt00vxqena4cteafexcumhe2q3sfqwzml674gt3p66xpx29hg03yhpqx372axnungrkqxcn5qtz58rqaqe79cgpu9pnkmdl2x24uyxv7l4au5ksgy64jpdq9df8m4nga3x3ya6qnpddgt9wph26g4wzv6sqs4qk9h68hjsdm4gc64u9cscvuakemx0sx9gke7pxwwwjulj5jednz63rcsq2hdnpdvcycfv74q6jgves8xnd6wxyx3j37a7m9hs4ezehkfj0mt240qza80u59x0e4j6c8sk7gwxkvwxw5fs2vzu9yvvnk4y2cckceww8pm5ygjp7fse2zsgl3hvrlyklrw5a9f3td4ynsufj3zx8q5k676gt9ggdnr2jy3pvp6qs7hgmqfc2j0n5kxzk2xxg292p7tsh88h3g9uy526wdps3tmzprvycwagk3xz6s6s67sv0rkf94axasegfrfd02cwvfn3ag0ej2my9f882rly5tfpsw4f27fxqm9qqsxzxtgdt69qxs2p2z699q9keu3ak3h8vu9k6av83dsn8pqk6qs343fyfyvmmhrfdrtf9uujerwapvc85n2cj0s4l0cts03ts2d3u4kah53kvl8r5clt9gsckcdnuuj9a428s463gqlcxlkwq2vp2p0qctcepzzykezclvvuf3x04av0da3t32mq2mztv96eppakknczh94hrved7ya276s9t97wxn7tn9m83c945zhz49yseu4k76lcmfesudc2u9hd9azshxzc2d90zee03lhqrltj5xgs7dlpm9d25j9avfzg25v0zw4zzdxm2att6gmu3d5zeaaj9zv3vw28wvp8pdzmq9k5r348th5l0qv2jrgx5y3qfpndzvuz34uz3fkk3vdky32g7yesg2scuf7kgr2uszf925333g3kgjp4x396fns4wzhlap6slfh537qqlxwdgv05u4kaff9hwtpp0hzp2ks0g3hpvugm5u8h3scdq08yxyxa9esm2fnf3sgterqxy8kjaxzcyd48evlehnsss4e34v89s3sy4qa5q2qh5jz7sykjmha5enke9hpdry6d5k9us7h2d5szklegwfkgz48krs5epfc0kz7dfjvqw85m8r0x84kejge4huesztw0yrarw9x3ug99uh2qd7y5lkw0v8e069ptd29pmhshehngt5zu625aftxf7crawgkzeckz5hhdqq6jd5ftqzcupme0nzhql3c4s3cn5gl58muqrnjj45qfvlfaz5xc5d9znpu2dfec5v5qz0mlrq4ehyltj3gdnrn8893vmmuhty686z8u8jxzrlgj3em80rfazqwqhnscnh8x2qlwhs8f0u044fjh4h73e862fe9xg8cwqu2f290tc8mgedckg5tj7mdwz2nfkkl7t3yxmx7ukza3xwhauqpt3s7vzdezyqx9tqv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IHp3N0ZYaHVL
            cHVWK2pHZ0RRcVhuUk1XRWl5YThKaThkYlpRYnBsSjREM0x2ZjBlZE1aZkwyOUky
            YVl2L3JwcStLb1NwUmlvV0JCRnZMMVovdmFMTUlWcXpBVEhxRU1aYU8xZmdGdlM2
            ZGxvbElTUEc5amZNY3dHK0ZrbFFVaHhoQ0lHa0hSUmxtZWpVREVFY2l2ZWJ0aDRk
            eStpNktuWkVVTW9mUHBGUzR1bEZiRDUySkdtdVlvYlpVY3RJblZIUlRYQ3VJb0Jm
            dit6RTkyTkJzZ21RT1hycDdwcDFIckdyZ2MyRFkwTkhJeFdJT2ZhTCtqcmNFNjMx
            L2psMUxvRnp6NFFLS3NITExrUThmR3JoczNjVGw5UzFseGJrRkFXOHRaalZhakMw
            R3pROEZscTNiS1hveEVkcjFNcm4vRGJ2QmlUWWZ0aEtUUU5CVDljSzVGZmpBdG1z
            YXJCNnhvblZHZFFUTFp6WG5ZQjQ0dmRTektZbUJBeUcxNVFGN0c4ZDZBdkd0Q3dJ
            OGpNZUFaNnQwMzd6L09DSUZMNkI4ZS84QXBxbk5NTFR0dm5OUlFBcnR1QXN0Z2xw
            SWk3c2ZGZG1teHpQeU84SXh4QzhWTEE0bUFtVkZneldDUFZFcldZaC9LbndDc1J4
            ZFNDQ1ExTDAzV2NweFVGWFBuOS9rM2dZVUFjOEl2b2M5Tmw2VlVzOVZoN1RHY3Fs
            QWpCQ3hZREJ4ZHhTanBuVWpkTFV5MkltNjlvTjNpTWxuQWE3N1pzV1NFeXplTTZQ
            WjVkRXVrU0JGeWswclZxRDdHMFc5b0VYZCthb2N3RUcrcnhuaW42bHFLR25rS2Jt
            V0VXNy9ZT1J0V0VvV2QxVnZQMUwrNE5NZFliaEVVWW55NVJSbHRRQmNkalRNdlNt
            N0IzSkdjVmZaUkRyRHdNTDAxUkpVd2FRamE0aU9kNjR4azRGaFllWU9DOUtNTkFF
            dDBXS2ZvVTlkZXREajM2Nnp0YW11SzhnUCtQS0NLSGhaRUpNb2pVa3g1bHRZRHA2
            SVBoUDU3S1JEN1pyb3c2c0UrMk9iejhCaTRpZ2JVTE5RTmRIQitXSGxhVGtaOHRv
            eXRLeUIvUHRBaTNWaWYvN3NXRFIxRDZ4cVVUd3BzeThXc3drUW1jbzhjaXdJaW45
            MkROb1dYUG9LUit6b2t3QVMvRXAvekRKdCtwVi9wT0NQN3hNbXpFaXhRU2FyVm9i
            MXYwNWVBaWw0N1daRk1EMklMZ2NzVEdTd29OeVVFaUlXKzhXdlZvZkJXNisrcjRI
            Z0ZmK2lKVWVKYTN6MWVwKzJKUXd2ZEZwcjJkaEdCcGo5U09EeGEwZkpKUFBHSUgy
            dmhhY0lTTWVNY09EU0dYb0lzc0hPYzVHNTJocmpqbXdtbUlvYWVKNE1QcnFyUkg1
            SmtweFFIdGhXam1WNGtkdzZvZ255OTVHVXU4QkVvVS9qdGF5bnZzaCtnMEpBSEp1
            UXZyQ0JWT2JORG00TU9rTDJQWERNYjN6eTE0N1V1a3dSbmllaVpURzJuSW9vR3Uv
            UmxtaUE5RVkwSVhxbTgzc2M3VkVKUHF2dzdXSlFQVTh4Y2JOaktVNGtkNlMxTWpu
            K2JzQ1h1Nkgrd2RRNkllUzlFckJFRnk4STJ6cU9Sb0dXU2ZGaTRwZjB3aTFEUUk2
            NklwMHJabFN5L2hMUUplV2k2cUJTTWpJa3FMSDhQR1VRV2pUVFl5R05GRDFVdmM2
            Ni9DYmV4MVZVVmFhQUhLZHJGbFNEVTQzd2FmNm4yZWthOFFlZ1JpaG9xS0NpUjkx
            UTI0YjdKNzRpMllES1Bsa0RXNXl1VVdyVjc1bitpS1NKRlRJSGI2aWIyT3FzUlkz
            Yk5sUU8rZyszdzdnMWFnSll1dEN5dFg0cVY1R0NOWDNVQVdvdjNNbXVvZWhFaU93
            RU5qeFQ3VnVnalZqRnc0RUdHMHRjNzVUbENWMGZ4SS9mcDlEWURsYURLMnhCZwps
            akZ0anRMKzBPbGd4UFJrN1lZNHhDNXBJamlTYWRwMHFBWEJDeGltK1VnCi0tLSAv
            T0Nyd094QzViMmo3VWo4WS9mWHJweFpTVkhzNVhmZkpyeWdxWStHQkVNClOxlh8T
            HZd/v9380QFoQFSUFbGMVfPhQKoRBVnfvxN6Slvxyy/65wEmflqxxOy5hMUQFAix
            sWYyJzdEDulKpSc=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xme50rm3zwqyzhqpjx078eandu987n4n2n6h0g7ludxlfvml4enydqkfjjhkrny0zs6k699076r5n36cjm76c582wk99kfqk8rmr0vsgswlkwlj5tdf0kgxpmr38c34n0pass6kxh9kc62zz8w6u65hcxlwjn0mahx6wqx6xnxpyve25n3qn3qh43f3vlufkrq6ftjt6833uvvkst9y3usyqlvpesj55vn3uwmqmuynsx7wzztgh7qsqz4z2f3unrx2spc935ade7t785rhafgdwpyj59xgf0zj4phsrrwmagzgwhzut9cdsjd44wu8fszahtn8hrf8gaztxz0xyc4khsd6leys2jfysglq98hcn4cchd8lu9wffjsyxt3e9gae8630n20c60g0pygar2jk8u0494d3f85rqg4e2fyq8ver8dut3p9c8rvvrgdy99q23qjfcvddt9canthzxr2jgz8p9khrj5zw2hrksh6r7y63jy94pn3uvwtk8xv09z2cgr0nhjaqp7azqraz2lu55x7ndfpa4sjpftczxe843r9u3pvu0tz5dy9pmgk2tm4dzy8qkgv8y4jlawxxf6fk8lwfk864hkf9ytsxnwg00evy2qf29938xyhkf3qurusuvysr8qws946sfpj7efv9c6px55qjlrp2ggu2vjqfkq0gk79nqf3ec2yy2u86t2yyddqq7yw33g2gygdgzw9h65w9q5zg9xg5m4sfe9rq29m7hp2p5yy4lge0wuetv0dyqvhwvylm6nfrm3skpuu4g78ffcp5mr8lq5nhvfwgjxfyrz0qma8lqqndwcjknhf5nfsj22p98qdmf0qdcfqy4y3zpf4jqzg6f02as24f8pjcns9pzfvyrvjrv87ujjpx2gvnhqgj7zjm2ywqpuusfq3zrguw96vrsm3j27r68spqht0cgr0stxu670cduv2cjahxs3w4y02xh6frnrj3a66rm9s9vn4dj4ygtnzajeqpyapsnqn5t8ag72sgwx6lj02vemskvkpytx5jwz2fpj9qze9qzcdextefvzslgf8qz6pystcy6aaz2zqevkdtz3pe0a9shqktzkmtxkhunrc4qx7fgjdexqc9rd6tnvf4xnyzjqzu5efwv0wdn4z6nh4gh2wf0xlzlzwm5jq4ce3sf3u24e888fp07vxqes5m5e8enue6x9j26w0wxqxfvtdtc9qr6zmcsrrd2np8rd33tq7s9k9ty9lyq4fkle3lyuugz5fkqgjgrqtcmesqeyxhwqu4elf6p4zqe46fqd4xhyy2cj9f2vwjde7eqd4xgr665dynk8xxvt9k2wwvmjh5zxqscql7ru46rpdpf4lj4kl68gdrr5tgt8s4mdy5gzeux797yf58qvmf96p67ne3fpdg4972hguxtvgfxxcu6pry2zxpe659hvaz0yzcdf92nfw4x6vp822dfdjy3w4ckq9hvuyf6xcrqa8g6pfmygtdcuqtuwqu5wx3y0dvg83umg3uv2pftu9cuqvwy3tmmtdgjzaj4z5za82qc049xyfps3zse8yajuzqrxv5mlyse2l0zj0k8rw5569f77ynvsupmffxmg3f5gm2uv4vt2e9t7wcjwxerqug8vjjwcwx932eu60p3ygd297m69853qs622ztkr7ttldm3zxw9jhcxya9444y0znn6qhc8qs8czq39x9f7e6d83xs5sk06zk65g00n0vedz39c572nuu7q4u3k5xnrcd52z3rygycym4wuqnnhx8xeyj6c8am7tmr38uzc400hyz5q92xtp3aualuz0ec40qhuw8ur4fy36pq23e9udw22ampdm8slvue5dg96m09zk3vhzhykhatc5qu2ps3sapzfmv6qt9v2u7fwaw2gktpvxvuaclpy0dqjck0mhuysmexqpsq899xz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dDVjd3RjN2w5ZGRudkJp
            TjJmSGRVWGtmcFY0YVpPZGJMUC9VTVk4dzFFCkUvQTVhM1p0UEpLYVlsMEVDb210
            QWF3MklZWmtkZGR6SVBuVjF2WmdWOW8KLS0tIHdNa0Y2Z2hpOGUxeGd6UnppNFV5
            NlI4NGdtTFhQdmxWS05HVHl2dG9sNncKNgjaRqUsTbHdSTuzpjPwwZhfhue+VO4i
            J1phj7B4Tii+ur83KABNUSPFWqR6RhFGhDMPVS/FHC49UidebMHB1Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age174yq43fu75xyuf5t92yeekejl6fx84zewy45wqzy538g2qx29clq3gfn3w
    lastmodified: "2026-08-16T05:02:54Z"
    mac: ENC[AES256_GCM,data:crPtXUqsZr9cDCYxuD9zbLYLfq+lCrd3i7D5DplBr6YWfz/vy4nmsavvNqlTBkQvvUyptA9dhkPKwSQB3Uyha2rGThcS//tz8Iy5TcMDQWXyDAMR6rg7Gei5wTwFFNlnDa0iFCWq83YxCangJ3zmfCRKIkwv2T3jounh2Ik8yFs=,iv:DckV7kVU9C0UKjHKi3bMBMSofvVuDiannhpAigTEOA8=,tag:otClKxv2i/d/j9Zbtg08kQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
