vpn:
    pk: ENC[AES256_GCM,data:FgFTNSSrR5n+MSoU6OH/JS2vT4nJdFdvPVNroiA7gBIrt3YBU9fsOfA2Sy0=,iv:JHqlUK+8m4TV1wbki4pxGfpdRS6IZ48XcmAgcHVQha0=,tag:1UX55M5Zy8IcPEy86zzFgA==,type:str]
syncthing:
    key: ENC[AES256_GCM,data:+Wow+ZWLZ5Gs63qfEynm5q3HmjYo2LMVtBOV9ff5EOT/h2Ux+ix+Q+TQ9ozd4m33iJZbF0o7Ub/yWD2SLXTiLCnWm2ZWS6bSIg0wnKXXaIR2grArVCJCjOYPRryVREMOcGG585IedkW+On1Ufuy2NRK6fGj1pfY=,iv:96Z8zXHgDUEObcK5GUzvhg0Ts1NXbLw+NP8Raxc5Qoo=,tag:oYBGUuHp/CcteAkpoFry6w==,type:str]
kdeconnect:
    key: ENC[AES256_GCM,data:1qSUrza5o+zNBAHdegGW0WzGrvzDklZq6jn3dn33Po8pnO4WFKlnVteXcLHS0ulHy5KHL7VcRcTedKTYOmEICTn1VcZ81igTDv569FnlwCYxkbCbAa/VIXRFuwrUEm7wELqCJqoJZm/RDP8CDhjlk3XuyhkGXD3zwmfaSCgt5IAo3A48h3/u8O4vpZI6swD/VyNvVNV4F1l/IcPRBL0pSOYizl0EvuZbeT7F45+zZSOe3HMvNqGoQCV0/cU90OQgDtgSecinahs0+t79H3CO9eXsGj78XY6Q8FNq0vFRmN6G8Am/mtrr/LFZSOLf+2AijA==,iv:Pdx6AG7JnkN7u57EiQBqyVxOt8jO7Zf8LpAdkXDGg5w=,tag:N/hajWKG+UxgxYdSHbdYgA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYRzhwcEJmcGJzVm1hVkJj
            NU9RTWs5VU84ZHJlVnYzTXFsM0FMWis3Sm5RCmVLMC9wOXpmUEFKVHdVeHBCSHZh
            cHlLRGNOanhJd0VHNEI0OXYrNzF5K1EKLS0tIDJSSGVPdFlINFpOWXBzckRRbE8v
            OVZONkNRWk11NUMwM1lwVUx1ZExOOUUKUF8u7wv8hS6jOZnoTpf9QUts2QrHS03g
            1Rw4ZUJc2aZJ63WAEmUlxkVmw13+FQhhZ4XB+1e5soOc3w4s9DzUsw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zmpz7zl6hjrqarz4w5lsnkrqw66e63np08pdt8c5rrdh70etlqwq03ksp7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTZmhCYnBjQ016Q2VIcmI2
            bCtiYk5tWXNkZ3MvQlUxcUVCUG5WWWFyQlhzCmZPZks5bzVXV0E1TnZkSGxXaC84
            M1p4SWhoS2IrSjZraElSNk5rclI3eGMKLS0tICsrZGNocnhINzFZZndUbUpvaVhs
            REQ5bkhpZUZhSXl6ampxUk8zd3ppa1EK3P/khwblHjcoQ1eqUed1fXlwItgdtJ1l
            q5B4TX+4XtLOTZ73iB8f8efYNn4D52wFWU+0PVj1taNFFEMI/cyt6Q==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n4q00k9aas6g7eexc7spv32j02m3wez2gcnucre0tx76swazv36q8qchnq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWUWxRaUl6NzhJNFVMRS96
            Zy9CeVdkYTYvT1B0T1djZGp5RVpNeEJwZnpBCkZtMERKWHkvNUN0c0VZcDBNckg1
            NjJSOVJhUmpIMWU4LzNvdms1eGtCSkEKLS0tIHNuNlFVM29xeTBEQXJTd1RjN21I
            dmdxOHluNGNlMlM5Q1N5ZDNZOURRZ2sKut+LlBRtkoBTKuJusMs4DYWzlwxkDdHb
            uAfE2poH+cFZPTIeK1A0lgb3MPpR8vD089vgynaCXmyI4G5+Ms0X2g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age174yq43fu75xyuf5t92yeekejl6fx84zewy45wqzy538g2qx29clq3gfn3w
    lastmodified: "2026-08-16T05:02:54Z"
    mac: ENC[AES256_GCM,data:crPtXUqsZr9cDCYxuD9zbLYLfq+lCrd3i7D5DplBr6YWfz/vy4nmsavvNqlTBkQvvUyptA9dhkPKwSQB3Uyha2rGThcS//tz8Iy5TcMDQWXyDAMR6rg7Gei5wTwFFNlnDa0iFCWq83YxCangJ3zmfCRKIkwv2T3jounh2Ik8yFs=,iv:DckV7kVU9C0UKjHKi3bMBMSofvVuDiannhpAigTEOA8=,tag:otClKxv2i/d/j9Zbtg08kQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
