vpn:
    pk: ENC[AES256_GCM,data:JgDFd7BSi2Ilbe+/RK/OWPuSMZdH/7Z5z43FLMzNqMuIt2zeRINyDDf4m0s=,iv:HaIHdMMNT214lx93jkJpiecBXNowvLEAcuZjntgEe+c=,tag:vLbJ3TKpgXs9Yud2cFxuxw==,type:str]
syncthing:
    key: ENC[AES256_GCM,data:du55Sg0Q7LYdwp4vjTOFP/1DU/In4dzpNDNTndJVx+9udtCe07+96Gy1zkzzWi9/Wm6sxdS0oO/Cze8OR2ccNtZovXg663X2iDTdlPouoSJzToq9Cx+vmfkKCkK/9T1uGIdhjYMgSZ20PJwEQ0ZTdjyujLDswap6NeGmkIozJiOCVXuRC3EOUFYr2OXcYOT5IbAXyT4GXuODh7BM3OuXANr5lYyaUN9rXZd8oqVn7nvhm0RWwr/2IujTCiEPb+ryTmBPrKyTaY2sr4FVIT9Oc3G9jS5Y0rPetwLw4cxhofubrUA63FVNEJBAIjiQZ0XqhJlollBWxK0awjy6emmvL2lgZZj0SUrTpYDPmYPDyGu9e8ihKrf13NRwecmTk+UM,iv:+BCQHAqVlOFl9jrgm1HRrSrY69zS/5OoLzAa5V2jNJk=,tag:76dhJm4vhoBl0kNfRQo+6A==,type:str]
kdeconnect:
    key: ENC[AES256_GCM,data:4u9Vk5O1RoYlqqlstkEQjZ0dj/M51k91MRx5Zs1SETrVBp2U97JJVwo2Q2+hIlu5VYXNBFNE18ZTStzmURZtKhDQa/pWo1/yy66UiMzYAF0FDUnMVrVx8WevvLQkZswSuTlxinJD+J9eJu5fv7bAtA8q9/kdwtL37p2eCtnzGVJjXoLc+Dp+7TSYmPUNYFZCnQ/vX/XE5oI5NqIhVCzt0EtmgsZe+COZDSibwOBYliNfTPrUIodai3R9fUGIoV7OeY1DTylCB5LMgc+mmrd3JBS8VhRh7UOtnE9mfDKOlIaXIUc=,iv:zbt2qqrfHsZzIyWgTzn8/55xaUUeGp8Up+RN9yRyGCQ=,tag:xwxcKUDIlHdR1rAyV/ry/w==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGhLaWo2L0wy
            Nzg0NUJiVHNuekRabnZNaGhUK1M2WkZGaWprRVIwS00yMEFZekoxK01aMklXRmZq
            MnJMVDVZdzdzZmdUZWhwcm9QaTlPNGlIbXhnMGJ3T0svcjZpQmwyMlZCT0FzWm1G
            Mll6OGQzK3VBWUQvQWZoaDdxV0tHUHhOWHFxK3YrV1gzNHlFTVp1TUQ0N1E4Rmtv
            V2FEUkphbTVNMFNwTFlHK2wyY3lVVmZNM2Z6OFZPNUNwcHhwRTZzZHRLSjNEbVlj
            cGtIMTM3dEVIZHVucjZ4OGdNN2Fpbm5Kc0svVkpNVzFDRUUyVGgrN0F1R3VoUmZX
            My9iOWJON0JSbENlU0Zxc2w3WXZxKzVpTUhLb3JTaHZTSk44OTlnU2Rwb0RSK05H
            QUNQR3pXelRBOXJjcnltQkhWczBhYndudFJQc2hWZFl5RWpLaDIrMU9xb1hIbVo1
            bkdFWXBmcjRWeHMyQVNTY0o1NzRtN0k3NTI1OUdnN3ovY21qaUFSZlJIdG82S0la
            Ty9ydHN3SXdONkMwYlFnbzVjc2tzbnNNZVRLUDhNcnNZVWJWQzQ0M0dJczRPTjBO
            TXJydDJkODFPM2RieVhHR0JZc1ppMEErTnN2a0FhaFZaY0VmTVZpWFVJdUdzUTZN
            VWtYQkNoZU4xbHpwdHYvM2NBaDlqZW9lckNRK3huNkRkdUMyTlNnQ0h2VGV5R3pm
            cmE5ZWtpdUlYRWNYZDB0eEZNUTJBNldJTktCWk1BTjcxdjJQWTVJT1JXNW9kSUt4
            WjhuYXUzUmZhUjlqcEI1ZDM2SGJ3ZW45MUoxUDdPYXUyNEFadXdxMWNNeFZjZkx5
            bkd6MnNMLy90REdYSDlhUXdmb0RjZm13RG9ZcTloL0NPblhJeE5ZUm9hNWt1RjRN
            cnpwU3JEWnkwcnJ4VU1XR0UzV0JUajhYajY2R0FiS0xxTW00RytSUG9RQXRPU0V6
            RzZBRXozSnpJOFJvY080U0lJc2UvODNEVDhkK3RtMUtWNGI5b0psSEFuRGcvQlpi
            ejdXSFBwTzFWdVBVN0N6TnZTd3pKNC82UE9OZVduN0N5TUUrbDNTMWpNN21KSVU3
            emI5TzFFdjZNWEE2TTBkZWdpN20rcVhRV0cwUEluK2RVaGsrSGpvdEhZbUlOUmE3
            czR5a2tyd25Tc25QOS9WYTVWN0JHbnlLVzV1QktDY1MwY2QvVEp2cE5qQTFncUpv
            RlNaSEhDWlAzQmplVDl0ZWk4a3kxYU0zdFAxL3JPWVZzT0NvamdzSUtkN3JsblJi
            ZnF5bXVQaG9BRld5dXYrd0E1WlN1ZVlKZXk5VEVlRHFoOG8rWWRlZUo1WUlnWkRw
            MWVPSHNRNTF4TE84a3Jyd0d6b0FKdzdpVnhkVmtmWVB3eVU1U2hPVHpoaHlHMERm
            QmVYTnJLZWIrK2laUUdBeFlXRVcrQ2NHdmh3Y3FRZlBzNnduRmFpL0NHSGNXNTd6
            M2gyRlZFeUdPNlBmN3RQbjROQ0QxUTdzWVhLOExBUEh3NTRnNTBNY0czVG9xWGlC
            SDF3WUlTWHZUdlFwSnZrTEdDT2UvaUdteTdGdzZCNmlJMCtZQzd5YWpzNXBEK3dS
            Ni9ubUlOSHBtM0pMK2NzWTBLU2lRRnlQQzQrTGdDWHdCNzZhTlRzT09zL0hIcDlj
            Ky9JWXpaNHZsWGh6Ynd1T1o5ZWpTejFnSmd1U1dHVW4yaTRCampQL1h4VHhkZ3Nh
            TXdtazZQeWlpSUhxU3RRY3pEaWhsVXY2RHM2TExJaWhseTMrNkNuakJsU2NtQTMw
            MEh2TlRMU3Q2bFJITEVmVTRTQ3JvSEttdVdIQXBHWFZDWmE2NXByaFV0SitwQlZ6
            TjdJK0p0eGlKZDBEdXVweG5oT01oQmdnV3pMbUgwV25sYllEWndDOHFCRExhekdC
            a3RqZkV6Z3EyUmEzZWlSQ29xT3N2N3dyWjdBZTNwZWFBdzJpSDh3Z1J5bGlaZwpy
            TjdoenpXUEhXcTZqcDJEdWVzNmE5SzVoTFFGMm5ZdTFsTm9KdklrdklZCi0tLSBv
            YXppYXJMWVVLN1FkMGZkRUJmSFZmNStGWlNIYThFamZhckRpb1VUNy93Cq3w/b4v
            CGPLK0iT8THw5W/vcZIQecui+FvGkNYQdFa/fWhQWV+OUwf+haRoYWRGuu9go7O1
            g7FLlvZUUMs6+c4=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq15zkgrl6kqmch899ejsehzdqvyudyz33uq65njscappkvfqm4tqermjgud0rddvq4rpryr5r5jx35c844fsr7245k72jtd755tdqmt6jgv84pt2g6kz0plkugknvr6s84x5f9s906qdlrwsmjveyu3egvv8mxhvfxhxtpw9qqvwmt7uf8jtk6sq7xgk49yau46ufr8qf2q05ycjyxvf57hpsrvlr2ylj3jg6j59uknsc8xsexvfrmwaar02w43wdfdwjz6x2pklycp5fr4za4zm3s0scyz5u00nrpgrr2sqwqn03xusjredazgsy5qrwjgy6jk06rhxp7cxs86w4h0gqtpewmes8yk5lhfjdajwucv8tr2nh049vtas8r5yplykjt96u2pm405wmuk3zrkgc2lwm5jnq222ur5vc3aqlee6qpdkdne69tcr7jv4j9vfwppzqnzwanane3qmd2dtvgc9nxugxz0z4m0mexrwtmt00vxqena4cteafexcumhe2q3sfqwzml674gt3p66xpx29hg03yhpqx372axnungrkqxcn5qtz58rqaqe79cgpu9pnkmdl2x24uyxv7l4au5ksgy64jpdq9df8m4nga3x3ya6qnpddgt9wph26g4wzv6sqs4qk9h68hjsdm4gc64u9cscvuakemx0sx9gke7pxwwwjulj5jednz63rcsq2hdnpdvcycfv74q6jgves8xnd6wxyx3j37a7m9hs4ezehkfj0mt240qza80u59x0e4j6c8sk7gwxkvwxw5fs2vzu9yvvnk4y2cckceww8pm5ygjp7fse2zsgl3hvrlyklrw5a9f3td4ynsufj3zx8q5k676gt9ggdnr2jy3pvp6qs7hgmqfc2j0n5kxzk2xxg292p7tsh88h3g9uy526wdps3tmzprvycwagk3xz6s6s67sv0rkf94axasegfrfd02cwvfn3ag0ej2my9f882rly5tfpsw4f27fxqm9qqsxzxtgdt69qxs2p2z699q9keu3ak3h8vu9k6av83dsn8pqk6qs343fyfyvmmhrfdrtf9uujerwapvc85n2cj0s4l0cts03ts2d3u4kah53kvl8r5clt9gsckcdnuuj9a428s463gqlcxlkwq2vp2p0qctcepzzykezclvvuf3x04av0da3t32mq2mztv96eppakknczh94hrved7ya276s9t97wxn7tn9m83c945zhz49yseu4k76lcmfesudc2u9hd9azshxzc2d90zee03lhqrltj5xgs7dlpm9d25j9avfzg25v0zw4zzdxm2att6gmu3d5zeaaj9zv3vw28wvp8pdzmq9k5r348th5l0qv2jrgx5y3qfpndzvuz34uz3fkk3vdky32g7yesg2scuf7kgr2uszf925333g3kgjp4x396fns4wzhlap6slfh537qqlxwdgv05u4kaff9hwtpp0hzp2ks0g3hpvugm5u8h3scdq08yxyxa9esm2fnf3sgterqxy8kjaxzcyd48evlehnsss4e34v89s3sy4qa5q2qh5jz7sykjmha5enke9hpdry6d5k9us7h2d5szklegwfkgz48krs5epfc0kz7dfjvqw85m8r0x84kejge4huesztw0yrarw9x3ug99uh2qd7y5lkw0v8e069ptd29pmhshehngt5zu625aftxf7crawgkzeckz5hhdqq6jd5ftqzcupme0nzhql3c4s3cn5gl58muqrnjj45qfvlfaz5xc5d9znpu2dfec5v5qz0mlrq4ehyltj3gdnrn8893vmmuhty686z8u8jxzrlgj3em80rfazqwqhnscnh8x2qlwhs8f0u044fjh4h73e862fe9xg8cwqu2f290tc8mgedckg5tj7mdwz2nfkkl7t3yxmx7ukza3xwhauqpt3s7vzdezyqx9tqv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IFJ1L3E0T05V
            ZEhLcjdUNzc4RzFwUHB4emh6UEpsckZHNlBNRjQ3ajlGTWI3eHUvc0JPS2JvWmgr
            TjFuR09tSEFzK3pqa2ZnK0k5bXBTZE9ncFhnRWUyQlU0K2R6UXFhVG9ENXNRaDBD
            czNDZXpvbDNMWW1ITWNqSm9ZdTU2L2l5RTdlandIMWpWWkIvdkdKNEJvSDNUUEtq
            cXc5dGhHYmxoRkZZVEoyaXZ0b0dNU1dxOTZWVUxkdDJDQlpFcnd1d0cwNmRYcEZN
            Z2V5QmMvR1ZxQ09JNkgzcCtDMzNndUxHQjlBUTU0dFRKeklMVWJMMm5NWGp5c0s3
            K0hkb3JsUDltaCsvR2swNmc0aDZ1RStaSGVhVnJwakVCSm9mTUJoeHhZTGp0N2hC
            ZUhPYkNaNE9EdzQ4WUpVdGtrMHdHZlU4NjVjV2U2akJ5T1RaS0Z6Tm9PVTVvWGw1
            aGRqRmI5Umt5ZW11UEhvaW50SEZVZTJxRm1ZVHVxWUFaZzRySklBcUx3N2piaUhz
            UWlxVVYyb2IrTXN6bGhmcHltakwxOXNFZGlGMHN1WFhuazM1b2VpYVJwTUsrdWF6
            cmFteS9kaWxyZ2pxZU5DNTIxN21IUWxGNERiNjk5bC84NmdSa3ErS01NVzg1dEta
            OXlIVldCZ0h5amJ5L3VldHhMY01lNHJRL3l5UC9mRDdyaUg2bGphOEVSOGYwYkVt
            c1dpd3EyUW9rS1M1T2drblV0MFRISWdPZEZPNjBFWi8ycm4xclJSREJONmllVWJr
            T3BBc3BoZFRzNC9nRkFyVTdPTUhlYzJaL1d4Rmk0NDdWUklTb3JSanVoSU5KaGRM
            UndGcitha2FZQ3hmbisrOURMZFhTb3lxalV1dW5ZZ3kzY0syY0ZNdWMrU242UnhU
            UWs2L3ZNRzdNRFJNUEFHek5Uczd4QVVhbHd1bURjUUJFdGQ0U2VsV29GV1M3VG83
            RVNPZEdXdk1ZdlRQenIxc0VVTGE2MkcvZE9KNWgxcGY4MFJFZy9nNnhjcis5Qm8v
            VE5idnJuN3FaRDYyRmdzeU1RTjNqK0pnWTNrdndhbVNIb3NvV1QzQjh0Slp6bHBm
            MmtBMnJDMm5Ca3N3WmlDQ0pmRHFSVXY2cnc2bElRV3BLalo3ZVIvZEpmdnNKYThy
            TW81TUxPakU0dDh1YWdLOVFCbGNaaTMvbjllbkllREpVZUhYNlJkOU5TZC9SUFdH
            RTAvRXJucEdFRFpRM2hzUnl0YlhScVcwVmFRKzQzR3MzYTJNengxK085WmtYOTZX
            VkF2SmhEZHhrdDNXU1NaSmtGMlcrUzVZczJNeUY4bC9nY0k0NjJlaDFjWEJ1VzJE
            Y3pMQmlTeHJPR3o2KzlWTm52aGF3NG1jZ2g5enRTQ3Q3UG8vOUhvWi94cnR5YmN5
            SG1vSzR6VUgwZkEwZ2NTYXRxRmk3V3dCVExLZEpLaEJLTUJpTkNSV2I1MmRRVndN
            THNVY0xUTHJXUzJ1UGZQMm91YkQ4dGljalVybTArNms4ZUszN2c1ZGxJdEMyYjdw
            cENweC9MaFgwYlRrWGpDUWd5NlMyVFExaXp4b1o5MUcvU1IyMUd3WmZWak9wVk9n
            MTdMMTJWZlV4WDd0QUFlN2xYV0hpdTQzYkg5N1QxM2pOMnhhZktabUdMQmdVajF4
            NFYvUkQwbkVaeXkrSHhwQWlULzdVZjYyRytwNlU5ak1yTEptVHJZYm0vR244WjVl
            alhQV3VENlpLa2JqaTVuYWpPajdhSDBNY3NUU2tlVmlQYkF0NXp5ZW1FYU5CQS8r
            bWZSVkJFMkR3dHFVZDdMbkM2SUJZY2lWMXlOeXRnSGZkdUJJbWk3Yk51QSthOUZF
            KzNzQlN4aGdxZDJtcVprQU5wcDdJWkg0RUhUSjF5VDVWKzRSckNLZGVDbXA2Umkr
            eURXbFVLV0I1cmg0K0tseHdYWUMrQWk4dHRWc1N0REtxLzhyTUpsbUNtTVdBQQpo
            bzJzYkRIcDdYOG03dGU4ZkJxS04xYmlDWDRiR1FoMEkzRk5NSEwyOFY4Ci0tLSBu
            Q0dzMEhJKzZzM2JrVWZ6RDRrMnArWHF6bWtYVVpxczF1Lzg1M2RmVlE4ChPUds0x
            M8MVif36eeu92o+bZo9Uc0WUfQTEm6zxwCvpF3u7qO75b3MdAPQ+QUZP39gGOT0g
            mNrWLIFdzcmPpOw=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xme50rm3zwqyzhqpjx078eandu987n4n2n6h0g7ludxlfvml4enydqkfjjhkrny0zs6k699076r5n36cjm76c582wk99kfqk8rmr0vsgswlkwlj5tdf0kgxpmr38c34n0pass6kxh9kc62zz8w6u65hcxlwjn0mahx6wqx6xnxpyve25n3qn3qh43f3vlufkrq6ftjt6833uvvkst9y3usyqlvpesj55vn3uwmqmuynsx7wzztgh7qsqz4z2f3unrx2spc935ade7t785rhafgdwpyj59xgf0zj4phsrrwmagzgwhzut9cdsjd44wu8fszahtn8hrf8gaztxz0xyc4khsd6leys2jfysglq98hcn4cchd8lu9wffjsyxt3e9gae8630n20c60g0pygar2jk8u0494d3f85rqg4e2fyq8ver8dut3p9c8rvvrgdy99q23qjfcvddt9canthzxr2jgz8p9khrj5zw2hrksh6r7y63jy94pn3uvwtk8xv09z2cgr0nhjaqp7azqraz2lu55x7ndfpa4sjpftczxe843r9u3pvu0tz5dy9pmgk2tm4dzy8qkgv8y4jlawxxf6fk8lwfk864hkf9ytsxnwg00evy2qf29938xyhkf3qurusuvysr8qws946sfpj7efv9c6px55qjlrp2ggu2vjqfkq0gk79nqf3ec2yy2u86t2yyddqq7yw33g2gygdgzw9h65w9q5zg9xg5m4sfe9rq29m7hp2p5yy4lge0wuetv0dyqvhwvylm6nfrm3skpuu4g78ffcp5mr8lq5nhvfwgjxfyrz0qma8lqqndwcjknhf5nfsj22p98qdmf0qdcfqy4y3zpf4jqzg6f02as24f8pjcns9pzfvyrvjrv87ujjpx2gvnhqgj7zjm2ywqpuusfq3zrguw96vrsm3j27r68spqht0cgr0stxu670cduv2cjahxs3w4y02xh6frnrj3a66rm9s9vn4dj4ygtnzajeqpyapsnqn5t8ag72sgwx6lj02vemskvkpytx5jwz2fpj9qze9qzcdextefvzslgf8qz6pystcy6aaz2zqevkdtz3pe0a9shqktzkmtxkhunrc4qx7fgjdexqc9rd6tnvf4xnyzjqzu5efwv0wdn4z6nh4gh2wf0xlzlzwm5jq4ce3sf3u24e888fp07vxqes5m5e8enue6x9j26w0wxqxfvtdtc9qr6zmcsrrd2np8rd33tq7s9k9ty9lyq4fkle3lyuugz5fkqgjgrqtcmesqeyxhwqu4elf6p4zqe46fqd4xhyy2cj9f2vwjde7eqd4xgr665dynk8xxvt9k2wwvmjh5zxqscql7ru46rpdpf4lj4kl68gdrr5tgt8s4mdy5gzeux797yf58qvmf96p67ne3fpdg4972hguxtvgfxxcu6pry2zxpe659hvaz0yzcdf92nfw4x6vp822dfdjy3w4ckq9hvuyf6xcrqa8g6pfmygtdcuqtuwqu5wx3y0dvg83umg3uv2pftu9cuqvwy3tmmtdgjzaj4z5za82qc049xyfps3zse8yajuzqrxv5mlyse2l0zj0k8rw5569f77ynvsupmffxmg3f5gm2uv4vt2e9t7wcjwxerqug8vjjwcwx932eu60p3ygd297m69853qs622ztkr7ttldm3zxw9jhcxya9444y0znn6qhc8qs8czq39x9f7e6d83xs5sk06zk65g00n0vedz39c572nuu7q4u3k5xnrcd52z3rygycym4wuqnnhx8xeyj6c8am7tmr38uzc400hyz5q92xtp3aualuz0ec40qhuw8ur4fy36pq23e9udw22ampdm8slvue5dg96m09zk3vhzhykhatc5qu2ps3sapzfmv6qt9v2u7fwaw2gktpvxvuaclpy0dqjck0mhuysmexqpsq899xz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgbVBRQ3FBIEJHQ0NzUW5W
            aHhtTHg1Um9ua0thUWIrbEN4UjEyb3NRY2R4SFgrblFRMVB5MjFZNVZpN3F6d0Qv
            cVc4KzViRndRbUhCVVBYeTdDNTZNcVl4bEI3WnFXVQpYTlAwZGJlUGROZERpblNr
            eUttdGtZaG1XdXJtYVV3QUpwSzUxQzNNUmRNCi0tLSBOWi82aFlsMENlbUdYc1Y0
            TW5GSjV5MGZBeWZmYVpPOWdsdm9aQUpNOHdJCjo8vcwubMGjUDauAl8BOiH9Xu0N
            cwlC/XP3Cu5bmcv7rVxcZlra4zY+FMnF6F+2V1fAZrOWz8UWm2yZjEcDCjQ=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1qd5s6fcv5upezjgzv4y39t0kfg0tgalwdfmf3elnccu5u87ctzgmxgmt756
    lastmodified: "2026-04-16T15:59:01Z"
    mac: ENC[AES256_GCM,data:DwoQtaceSWggt6yAofIaP+Vkn80HsMzQfKxhx55nMzqqFa5i/+uanI1AVBkwwVxOG87B1QznOMnbAPyOl62IylWrTrMgwpL7KkrJXawDcLO1n/F5hcRra7NFFcSO/pTmzAk16F6fJmFA7ptakvV17uUjFJSba9+WBQ2UaO9qrBE=,iv:07Vk2bU6GaF6QDN/oS14L7Sfi/ll4Y8Hi5o6qf+NVSk=,tag:pQAd4n8Un4ZGOzFE/vmjnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
