vpn:
    pk: ENC[AES256_GCM,data:JgDFd7BSi2Ilbe+/RK/OWPuSMZdH/7Z5z43FLMzNqMuIt2zeRINyDDf4m0s=,iv:HaIHdMMNT214lx93jkJpiecBXNowvLEAcuZjntgEe+c=,tag:vLbJ3TKpgXs9Yud2cFxuxw==,type:str]
syncthing:
    key: ENC[AES256_GCM,data:du55Sg0Q7LYdwp4vjTOFP/1DU/In4dzpNDNTndJVx+9udtCe07+96Gy1zkzzWi9/Wm6sxdS0oO/Cze8OR2ccNtZovXg663X2iDTdlPouoSJzToq9Cx+vmfkKCkK/9T1uGIdhjYMgSZ20PJwEQ0ZTdjyujLDswap6NeGmkIozJiOCVXuRC3EOUFYr2OXcYOT5IbAXyT4GXuODh7BM3OuXANr5lYyaUN9rXZd8oqVn7nvhm0RWwr/2IujTCiEPb+ryTmBPrKyTaY2sr4FVIT9Oc3G9jS5Y0rPetwLw4cxhofubrUA63FVNEJBAIjiQZ0XqhJlollBWxK0awjy6emmvL2lgZZj0SUrTpYDPmYPDyGu9e8ihKrf13NRwecmTk+UM,iv:+BCQHAqVlOFl9jrgm1HRrSrY69zS/5OoLzAa5V2jNJk=,tag:76dhJm4vhoBl0kNfRQo+6A==,type:str]
kdeconnect:
    key: ENC[AES256_GCM,data:4u9Vk5O1RoYlqqlstkEQjZ0dj/M51k91MRx5Zs1SETrVBp2U97JJVwo2Q2+hIlu5VYXNBFNE18ZTStzmURZtKhDQa/pWo1/yy66UiMzYAF0FDUnMVrVx8WevvLQkZswSuTlxinJD+J9eJu5fv7bAtA8q9/kdwtL37p2eCtnzGVJjXoLc+Dp+7TSYmPUNYFZCnQ/vX/XE5oI5NqIhVCzt0EtmgsZe+COZDSibwOBYliNfTPrUIodai3R9fUGIoV7OeY1DTylCB5LMgc+mmrd3JBS8VhRh7UOtnE9mfDKOlIaXIUc=,iv:zbt2qqrfHsZzIyWgTzn8/55xaUUeGp8Up+RN9yRyGCQ=,tag:xwxcKUDIlHdR1rAyV/ry/w==,type:str]
sops:
    age:
        - recipient: age1zmpz7zl6hjrqarz4w5lsnkrqw66e63np08pdt8c5rrdh70etlqwq03ksp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1bFlpRE9xTk5ZZDRxSzZk
            S0ZBTERmWWUza3RTK1ZHb1VlbHppaG1TakdZCmJTbjM4QlJrbHhSY215eGo1RENC
            azJ2blVIbDNOMkRSZXRaYzErZnpJaDAKLS0tIFg2ZTY3bVhVNUJqUXZZOGViMDhN
            cm80V01ETHF1SGkzV1JMQi9McTFxTjQKO07McISWm1Ga3auxPfMsLppzXN2p3kRU
            H3065ydNUbNoQzxLAnoaSqShDKoxzB/lArHqu0GihcTN6avoiI72lw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n4q00k9aas6g7eexc7spv32j02m3wez2gcnucre0tx76swazv36q8qchnq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQbUxiKzZ5aVRTRzY5Y1dY
            TmZBdDdiQ1VLVWhJQUdZeURtWmk1NVhTOG1NCi9jSEI5aWcraGwrZC9nSS9sclMz
            NWpsZG9heTJYUGw2eVZoaHFyR1RUMkEKLS0tIE1ZdG5xU1YycG1TZlFjRWc1NzMy
            TXRDOTBITXdGVmJGV1FNbVVLVjRVaDAKFzedrXiKlLPPOGV/RQ1LfwBCW16DpNp4
            ZkZUuOOLwsh6NzGtu25dZVZVkQANU4KMc4wCx/H3t5K/NlvnTegUtw==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1tag1qd5s6fcv5upezjgzv4y39t0kfg0tgalwdfmf3elnccu5u87ctzgmxgmt756
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgenhrckNBIEJDeVJtSVZE
            TGcvdG5KQUNrU1dTUnlGdWpVU2E1cG9RYzJhRjF0a1FYaElGWlhNWlJ5TFNZb09B
            a3F0Y0JtZ3lYQzd1MWQ3Ry9ROVNxMlhsZEJycENmUQpRYzBmc3EzZkx6Mkx1L3Jq
            Nkt0c1VWSGh1VWVJd0cwRURPUndFL1l5bXYwCi0tLSBFRGcxaXgzTmtLdHhMdGR2
            SloveEl1b0hTZW03M2tndEpLVHlwYndpQW9JCil3ANMrKGFFelm7hwGq0wGM4cH9
            taM5oIVg1BPuGxkd8uRJyv+0KON0qZ/Sqgckq9EPkh3jToFluCXFEDXUTsg=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T15:59:01Z"
    mac: ENC[AES256_GCM,data:DwoQtaceSWggt6yAofIaP+Vkn80HsMzQfKxhx55nMzqqFa5i/+uanI1AVBkwwVxOG87B1QznOMnbAPyOl62IylWrTrMgwpL7KkrJXawDcLO1n/F5hcRra7NFFcSO/pTmzAk16F6fJmFA7ptakvV17uUjFJSba9+WBQ2UaO9qrBE=,iv:07Vk2bU6GaF6QDN/oS14L7Sfi/ll4Y8Hi5o6qf+NVSk=,tag:pQAd4n8Un4ZGOzFE/vmjnA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
