local vscode = require("vscode")
vim.keymap.set("n", "<leader>e", function() vscode.call('workbench.action.toggleSidebarVisibility') end)
vim.keymap.set("n", "<leader>t", function() vscode.call('workbench.actions.view.problems') end)
vim.keymap.set("n", "<c-o>", function() vscode.call('workbench.action.navigateBack') end)
vim.keymap.set("n", "<c-i>", function() vscode.call('workbench.action.navigateForward') end)
vim.keymap.set("n", "<leader>f", function() vscode.call('editor.action.formatDocument') end)
vim.keymap.set("n", "<leader>q", function() vscode.call('vscode-neovim.stop') end)
vim.keymap.set("n", "<leader>ca", function() vscode.call('editor.action.quickFix') end)
vim.keymap.set("n", "<leader>cr", function() vscode.call('editor.action.rename') end)
vim.keymap.set("n", "[d", function() vscode.call('editor.action.marker.prev') end)
vim.keymap.set("n", "]d", function() vscode.call('editor.action.marker.next') end)
vim.keymap.set("n", "gl", function() vscode.call('editor.action.marker.next') end)
vim.keymap.set("n", "gn", function() vscode.call('editor.action.referenceSearch.trigger') end)
vim.keymap.set("n", "<leader>pq", function() vscode.call('workbench.action.openRecent') end)
vim.keymap.set("n", "<leader>ps", function() vscode.call('workbench.action.gotoSymbol') end)
vim.keymap.set("n", "<leader>pS", function() vscode.call('workbench.action.showAllSymbols') end)
vim.keymap.set("n", "<leader>pg", function() vscode.call('workbench.action.findInFiles') end)
vim.keymap.set("n", "<leader>pr", function() vscode.call('references-view.findReferences') end)
vim.keymap.set("n", "<leader>pf", function() vscode.call('workbench.action.quickOpen') end)
vim.opt.cmdheight = 1
vim.notify = vscode.notify
