local M = {}

M.apply = function(colors)
  vim.cmd("hi clear")
  if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
  end
  vim.o.termguicolors = true
  vim.g.colors_name = "nix"

  local highlights = {
    Normal = { fg = colors.fg1, bg = colors.bg0 },
    NormalFloat = { link = "Normal" },
    NormalNC = { link = "Normal" },
    Folded = { fg = colors.fg4 },
    FoldColumn = { link = "Normal" },
    SignColumn = { link = "Normal" },
    NonText = { fg = colors.bg2 },
    Conceal = { fg = colors.blue },
    EndOfBuffer = { link = "NonText" },
    Whitespace = { fg = colors.bg2 },

    -- Cursor & Lines
    Cursor = { reverse = true },
    vCursor = { link = "Cursor" },
    iCursor = { link = "Cursor" },
    lCursor = { link = "Cursor" },
    CursorLine = { bg = colors.bg1 },
    CursorColumn = { link = "CursorLine" },
    ColorColumn = { link = "CursorLine" },
    LineNr = { link = "Normal" },
    LineNrAbove = { link = "Comment" },
    LineNrBelow = { link = "Comment" },
    CursorLineNr = { link = "Normal" },

    -- Borders & Status
    WinSeparator = { link = "NonText" },
    StatusLine = { link = "WinSeparator" },
    StatusLineNC = { link = "StatusLine" },
    WinBar = { link = "WinSeparator" },
    WinBarNC = { link = "WinSeparator" },
    FloatBorder = { link = "NonText" },
    LspInfoBorder = { link = "NonText" },
    TabLineFill = { fg = colors.bg3, bg = colors.bg1 },
    TabLineSel = { fg = colors.green, bg = colors.bg1, bold = true },
    TabLine = { link = "TabLineFill" },
    QuickFixLine = { fg = colors.magenta },

    -- Search & Selection
    Visual = { bg = colors.bg2 },
    VisualNOS = { link = "Visual" },
    Search = { fg = colors.yellow, reverse = true },
    IncSearch = { fg = colors.orange, reverse = true },
    CurSearch = { link = "IncSearch" },
    MatchParen = { bg = colors.bg3, bold = true },
    YankyYanked = { link = "IncSearch" },

    -- Messages & Typography
    ErrorMsg = { fg = colors.bg0, bg = colors.red, bold = true },
    WarningMsg = { fg = colors.red, bold = true },
    MoreMsg = { fg = colors.yellow, bold = true },
    ModeMsg = { fg = colors.yellow, bold = true },
    Question = { fg = colors.orange, bold = true },
    Title = { fg = colors.green, bold = true },
    Directory = { fg = colors.green, bold = true },
    SpecialKey = { fg = colors.fg4 },
    Underlined = { fg = colors.blue, underline = true },
    Bold = { bold = true },
    Italic = { italic = true },

    -- Spelling
    SpellCap = { undercurl = true, sp = colors.blue },
    SpellBad = { undercurl = true, sp = colors.red },
    SpellLocal = { undercurl = true, sp = colors.cyan },
    SpellRare = { undercurl = true, sp = colors.magenta },

    -- Pmenu
    Pmenu = { link = "Normal" },
    PmenuSel = { fg = colors.bg2, bg = colors.blue, bold = true },
    PmenuSbar = { bg = colors.bg2 },
    PmenuThumb = { bg = colors.fg4 },
    PmenuBorder = { link = "NonText" },

    -- Core Syntax
    Comment = { fg = colors.fg4 },
    String = { fg = colors.green },
    Character = { fg = colors.magenta },
    Number = { fg = colors.magenta },
    Float = { fg = colors.magenta },
    Boolean = { fg = colors.magenta },
    Function = { fg = colors.green, bold = true },
    Identifier = { fg = colors.blue },
    Keyword = { fg = colors.red },
    Conditional = { fg = colors.red },
    Repeat = { fg = colors.red },
    Exception = { fg = colors.red },
    Operator = { fg = colors.orange },
    Type = { fg = colors.yellow },
    Typedef = { fg = colors.yellow },
    Structure = { fg = colors.cyan },
    Define = { fg = colors.cyan },
    Macro = { fg = colors.cyan },
    PreProc = { fg = colors.cyan },
    Include = { fg = colors.cyan },
    PreCondit = { fg = colors.cyan },
    Label = { fg = colors.red },
    Constant = { fg = colors.magenta },
    Special = { fg = colors.orange },
    SpecialChar = { fg = colors.red },
    Statement = { fg = colors.red },
    StorageClass = { fg = colors.orange },
    Tag = { fg = colors.cyan },
    Todo = { fg = colors.bg0, bg = colors.yellow, bold = true },
    Done = { fg = colors.orange, bold = true },
    Delimiter = { fg = colors.orange },

    -- Tree-sitter
    ["@comment"] = { link = "Comment" },
    ["@comment.todo"] = { link = "Todo" },
    ["@comment.note"] = { fg = colors.magenta, bold = true },
    ["@comment.warning"] = { link = "WarningMsg" },
    ["@comment.error"] = { link = "ErrorMsg" },
    ["@string"] = { link = "String" },
    ["@string.regex"] = { link = "String" },
    ["@string.regexp"] = { link = "String" },
    ["@string.escape"] = { link = "SpecialChar" },
    ["@string.special"] = { link = "SpecialChar" },
    ["@string.special.path"] = { link = "Underlined" },
    ["@string.special.symbol"] = { link = "Identifier" },
    ["@string.special.url"] = { link = "Underlined" },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "SpecialChar" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@float"] = { link = "Float" },
    ["@boolean"] = { link = "Boolean" },
    ["@function"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.call"] = { link = "Function" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Special" },
    ["@parameter"] = { link = "Identifier" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Conditional" },
    ["@keyword.debug"] = { fg = colors.red },
    ["@keyword.directive"] = { link = "PreProc" },
    ["@keyword.directive.define"] = { link = "Define" },
    ["@keyword.exception"] = { link = "Exception" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "Include" },
    ["@keyword.operator"] = { fg = colors.red },
    ["@keyword.repeat"] = { link = "Repeat" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.storage"] = { link = "StorageClass" },
    ["@conditional"] = { link = "Conditional" },
    ["@repeat"] = { link = "Repeat" },
    ["@debug"] = { fg = colors.red },
    ["@label"] = { link = "Label" },
    ["@include"] = { link = "Include" },
    ["@exception"] = { link = "Exception" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { link = "Type" },
    ["@type.definition"] = { link = "Typedef" },
    ["@type.qualifier"] = { link = "Type" },
    ["@storageclass"] = { link = "StorageClass" },
    ["@attribute"] = { link = "PreProc" },
    ["@field"] = { link = "Identifier" },
    ["@property"] = { link = "Identifier" },
    ["@variable"] = { fg = colors.fg1 },
    ["@variable.builtin"] = { link = "Special" },
    ["@variable.member"] = { link = "Identifier" },
    ["@variable.parameter"] = { link = "Identifier" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Special" },
    ["@constant.macro"] = { link = "Define" },
    ["@markup"] = { fg = colors.fg1 },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.heading"] = { link = "Title" },
    ["@markup.raw"] = { link = "String" },
    ["@markup.math"] = { link = "Special" },
    ["@markup.environment"] = { link = "Macro" },
    ["@markup.environment.name"] = { link = "Type" },
    ["@markup.link"] = { link = "Underlined" },
    ["@markup.link.label"] = { link = "SpecialChar" },
    ["@markup.list"] = { link = "Delimiter" },
    ["@markup.list.checked"] = { fg = colors.green },
    ["@markup.list.unchecked"] = { fg = colors.fg4 },
    ["@diff.plus"] = { fg = colors.green },
    ["@diff.minus"] = { fg = colors.red },
    ["@diff.delta"] = { fg = colors.cyan },
    ["@module"] = { fg = colors.fg1 },
    ["@namespace"] = { fg = colors.fg1 },
    ["@symbol"] = { link = "Identifier" },
    ["@text"] = { fg = colors.fg1 },
    ["@text.strong"] = { bold = true },
    ["@text.emphasis"] = { italic = true },
    ["@text.underline"] = { underline = true },
    ["@text.strike"] = { strikethrough = true },
    ["@text.title"] = { link = "Title" },
    ["@text.literal"] = { link = "String" },
    ["@text.uri"] = { link = "Underlined" },
    ["@text.math"] = { link = "Special" },
    ["@text.environment"] = { link = "Macro" },
    ["@text.environment.name"] = { link = "Type" },
    ["@text.reference"] = { link = "Constant" },
    ["@text.todo"] = { link = "Todo" },
    ["@text.todo.checked"] = { fg = colors.green },
    ["@text.todo.unchecked"] = { fg = colors.fg4 },
    ["@text.note"] = { fg = colors.magenta, bold = true },
    ["@text.note.comment"] = { fg = colors.magenta, bold = true },
    ["@text.warning"] = { link = "WarningMsg" },
    ["@text.danger"] = { link = "ErrorMsg" },
    ["@text.danger.comment"] = { fg = colors.bg0, bg = colors.red, bold = true },
    ["@text.diff.add"] = { fg = colors.green },
    ["@text.diff.delete"] = { fg = colors.red },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Delimiter" },
    ["@tag"] = { link = "Tag" },
    ["@tag.attribute"] = { link = "Identifier" },
    ["@tag.delimiter"] = { link = "Delimiter" },

    -- LSP
    ["@lsp.type.class"] = { link = "@type" },
    ["@lsp.type.comment"] = { link = "@comment" },
    ["@lsp.type.decorator"] = { link = "@macro" },
    ["@lsp.type.enum"] = { link = "@type" },
    ["@lsp.type.enumMember"] = { link = "@constant" },
    ["@lsp.type.function"] = { link = "@function" },
    ["@lsp.type.interface"] = { link = "@constructor" },
    ["@lsp.type.macro"] = { link = "@macro" },
    ["@lsp.type.method"] = { link = "@method" },
    ["@lsp.type.modifier.java"] = { fg = colors.red },
    ["@lsp.type.namespace"] = { link = "@namespace" },
    ["@lsp.type.parameter"] = { link = "@parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "@type" },
    ["@lsp.type.type"] = { link = "@type" },
    ["@lsp.type.typeParameter"] = { link = "@type.definition" },
    ["@lsp.type.variable"] = { link = "@variable" },
    LspReferenceRead = { fg = colors.yellow, bold = true },
    LspReferenceText = { fg = colors.yellow, bold = true },
    LspReferenceWrite = { fg = colors.orange, bold = true },
    LspCodeLens = { fg = colors.fg4 },
    LspSignatureActiveParameter = { link = "Search" },
    LspInlayHint = { link = "Comment" },

    -- Diagnostics
    DiagnosticError = { fg = colors.red },
    DiagnosticWarn = { fg = colors.yellow },
    DiagnosticInfo = { fg = colors.blue },
    DiagnosticHint = { fg = colors.cyan },
    DiagnosticOk = { fg = colors.green },
    DiagnosticDeprecated = { strikethrough = true },
    DiagnosticSignError = { fg = colors.red },
    DiagnosticSignWarn = { fg = colors.yellow },
    DiagnosticSignInfo = { fg = colors.blue },
    DiagnosticSignHint = { fg = colors.cyan },
    DiagnosticSignOk = { fg = colors.green },
    DiagnosticUnderlineError = { undercurl = true, sp = colors.red },
    DiagnosticUnderlineWarn = { undercurl = true, sp = colors.yellow },
    DiagnosticUnderlineInfo = { undercurl = true, sp = colors.blue },
    DiagnosticUnderlineHint = { undercurl = true, sp = colors.cyan },
    DiagnosticUnderlineOk = { undercurl = true, sp = colors.green },
    DiagnosticFloatingError = { fg = colors.red },
    DiagnosticFloatingWarn = { fg = colors.orange },
    DiagnosticFloatingInfo = { fg = colors.blue },
    DiagnosticFloatingHint = { fg = colors.cyan },
    DiagnosticFloatingOk = { fg = colors.green },
    DiagnosticVirtualTextError = { fg = colors.red },
    DiagnosticVirtualTextWarn = { fg = colors.yellow },
    DiagnosticVirtualTextInfo = { fg = colors.blue },
    DiagnosticVirtualTextHint = { fg = colors.cyan },
    DiagnosticVirtualTextOk = { fg = colors.green },

    -- Diff
    DiffAdd = { bg = colors.bg_green },
    DiffChange = { bg = colors.bg_cyan },
    DiffDelete = { bg = colors.bg_red },
    DiffText = { fg = colors.bg0, bg = colors.yellow },
    diffAdded = { link = "DiffAdd" },
    diffRemoved = { link = "DiffDelete" },
    diffChanged = { link = "DiffChange" },
    diffFile = { fg = colors.orange },
    diffNewFile = { fg = colors.yellow },
    diffOldFile = { fg = colors.orange },
    diffLine = { fg = colors.blue },
    diffIndexLine = { link = "diffChanged" },
    DiffviewStatusModified = { fg = colors.green, bold = true },
    DiffviewFilePanelInsertions = { fg = colors.green, bold = true },
    DiffviewFilePanelDeletions = { fg = colors.red, bold = true },

    -- Git
    GitSignsAdd = { fg = colors.green },
    GitSignsChange = { fg = colors.orange },
    GitSignsDelete = { fg = colors.red },
    gitcommitSelectedFile = { fg = colors.green },
    gitcommitDiscardedFile = { fg = colors.red },

    -- FzfLua
    FzfLuaBorder = { link = "NonText" },
    FzfLuaDirPart = { fg = colors.bg3 },

    -- Blink
    BlinkCmpMenuBorder = { link = "NonText" },
    BlinkCmpDoc = { link = "Normal" },
    BlinkCmpDocBorder = { link = "NonText" },
    BlinkCmpDocSeparator = { link = "NonText" },
    BlinkCmpSignatureHelp = { link = "Normal" },
    BlinkCmpSignatureHelpBorder = { link = "NonText" },
    BlinkCmpLabel = { fg = colors.fg0 },
    BlinkCmpLabelDeprecated = { fg = colors.fg1 },
    BlinkCmpLabelMatch = { fg = colors.blue, bold = true },
    BlinkCmpLabelDetail = { fg = colors.fg4 },
    BlinkCmpLabelDescription = { fg = colors.fg4 },
    BlinkCmpSource = { fg = colors.fg4 },
    BlinkCmpGhostText = { fg = colors.bg3 },
    BlinkCmpKindText = { fg = colors.orange },
    BlinkCmpKindVariable = { fg = colors.orange },
    BlinkCmpKindMethod = { fg = colors.blue },
    BlinkCmpKindFunction = { fg = colors.blue },
    BlinkCmpKindConstructor = { fg = colors.yellow },
    BlinkCmpKindUnit = { fg = colors.blue },
    BlinkCmpKindField = { fg = colors.blue },
    BlinkCmpKindClass = { fg = colors.yellow },
    BlinkCmpKindInterface = { fg = colors.yellow },
    BlinkCmpKindModule = { fg = colors.blue },
    BlinkCmpKindProperty = { fg = colors.blue },
    BlinkCmpKindValue = { fg = colors.orange },
    BlinkCmpKindEnum = { fg = colors.yellow },
    BlinkCmpKindOperator = { fg = colors.yellow },
    BlinkCmpKindKeyword = { fg = colors.magenta },
    BlinkCmpKindEvent = { fg = colors.magenta },
    BlinkCmpKindReference = { fg = colors.magenta },
    BlinkCmpKindColor = { fg = colors.magenta },
    BlinkCmpKindSnippet = { fg = colors.green },
    BlinkCmpKindFile = { fg = colors.blue },
    BlinkCmpKindFolder = { fg = colors.blue },
    BlinkCmpKindEnumMember = { fg = colors.cyan },
    BlinkCmpKindConstant = { fg = colors.orange },
    BlinkCmpKindStruct = { fg = colors.yellow },
    BlinkCmpKindTypeParameter = { fg = colors.yellow },

    -- Debug
    debugPC = { fg = colors.bg0, bg = colors.green },
    debugBreakpoint = { fg = colors.red, bg = colors.bg1 },
    DapBreakpointSymbol = { fg = colors.red, bg = colors.bg1 },
    DapStoppedSymbol = { fg = colors.green, bg = colors.bg1 },
    DapUIBreakpointsCurrentLine = { fg = colors.yellow },
    DapUIBreakpointsDisabledLine = { fg = colors.fg4 },
    DapUIBreakpointsInfo = { fg = colors.cyan },
    DapUIBreakpointsLine = { fg = colors.yellow },
    DapUIBreakpointsPath = { fg = colors.blue },
    DapUICurrentFrameName = { fg = colors.magenta },
    DapUIDecoration = { fg = colors.magenta },
    DapUIEndofBuffer = { link = "EndOfBuffer" },
    DapUIFloatBorder = { fg = colors.cyan },
    DapUILineNumber = { fg = colors.yellow },
    DapUIModifiedValue = { fg = colors.red },
    DapUIPlayPause = { fg = colors.green, bg = colors.bg1 },
    DapUIRestart = { fg = colors.green, bg = colors.bg1 },
    DapUIScope = { fg = colors.blue },
    DapUISource = { fg = colors.fg1 },
    DapUIStepBack = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepInto = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOut = { fg = colors.blue, bg = colors.bg1 },
    DapUIStepOver = { fg = colors.blue, bg = colors.bg1 },
    DapUIStop = { fg = colors.red, bg = colors.bg1 },
    DapUIStoppedThread = { fg = colors.blue },
    DapUIThread = { fg = colors.blue },
    DapUIType = { fg = colors.orange },
    DapUIUnavailable = { fg = colors.fg4 },
    DapUIWatchesEmpty = { fg = colors.fg4 },
    DapUIWatchesError = { fg = colors.red },
    DapUIWatchesValue = { fg = colors.yellow },
    DapUIWinSelect = { fg = colors.yellow },

    -- Rainbow Treesitter
    RainbowRed = { fg = colors.red },
    RainbowOrange = { fg = colors.orange },
    RainbowYellow = { fg = colors.yellow },
    RainbowGreen = { fg = colors.cyan },
    RainbowBlue = { fg = colors.blue },
    RainbowCyan = { fg = colors.green },
    RainbowPurple = { fg = colors.magenta },
    TSRainbowRed = { link = "RainbowRed" },
    TSRainbowOrange = { link = "RainbowOrange" },
    TSRainbowYellow = { link = "RainbowYellow" },
    TSRainbowGreen = { link = "RainbowGreen" },
    TSRainbowBlue = { link = "RainbowBlue" },
    TSRainbowCyan = { link = "RainbowCyan" },
    TSRainbowViolet = { link = "RainbowPurple" },
    RainbowDelimiterRed = { link = "RainbowRed" },
    RainbowDelimiterOrange = { link = "RainbowOrange" },
    RainbowDelimiterYellow = { link = "RainbowYellow" },
    RainbowDelimiterGreen = { link = "RainbowGreen" },
    RainbowDelimiterBlue = { link = "RainbowBlue" },
    RainbowDelimiterCyan = { link = "RainbowCyan" },
    RainbowDelimiterViolet = { link = "RainbowPurple" },

    -- Language Specific
    htmlTag = { fg = colors.cyan, bold = true },
    htmlEndTag = { fg = colors.cyan, bold = true },
    htmlTagName = { fg = colors.blue },
    htmlArg = { fg = colors.orange },
    htmlTagN = { fg = colors.fg1 },
    htmlSpecialTagName = { fg = colors.blue },
    htmlLink = { fg = colors.fg4, underline = true },
    htmlSpecialChar = { fg = colors.red },
    htmlBold = { fg = colors.fg0, bold = true },
    htmlBoldUnderline = { fg = colors.fg0, bold = true, underline = true },
    htmlBoldItalic = { fg = colors.fg0, bold = true, italic = true },
    htmlBoldUnderlineItalic = { fg = colors.fg0, bold = true, italic = true, underline = true },
    htmlUnderline = { fg = colors.fg0, underline = true },
    htmlUnderlineItalic = { fg = colors.fg0, italic = true, underline = true },
    htmlItalic = { fg = colors.fg0, italic = true },
    xmlTag = { fg = colors.cyan, bold = true },
    xmlEndTag = { fg = colors.cyan, bold = true },
    xmlTagName = { fg = colors.blue },
    xmlEqual = { fg = colors.blue },
    xmlDocTypeDecl = { fg = colors.fg4 },
    xmlDocTypeKeyword = { fg = colors.magenta },
    xmlCdataStart = { fg = colors.fg4 },
    xmlCdataCdata = { fg = colors.magenta },
    xmlAttrib = { fg = colors.orange },
    xmlProcessingDelim = { fg = colors.fg4 },
    xmlAttribPunct = { fg = colors.fg4 },
    xmlEntity = { fg = colors.red },
    xmlEntityPunct = { fg = colors.red },
    docbkKeyword = { fg = colors.cyan, bold = true },
    dtdFunction = { fg = colors.fg4 },
    dtdTagName = { fg = colors.magenta },
    dtdParamEntityPunct = { fg = colors.fg4 },
    dtdParamEntityDPunct = { fg = colors.fg4 },
    cssBraces = { fg = colors.blue },
    cssFunctionName = { fg = colors.yellow },
    cssIdentifier = { fg = colors.orange },
    cssClassName = { fg = colors.green },
    cssColor = { fg = colors.blue },
    cssSelectorOp = { fg = colors.blue },
    cssSelectorOp2 = { fg = colors.blue },
    cssImportant = { fg = colors.green },
    cssVendor = { fg = colors.fg1 },
    cssTextProp = { fg = colors.cyan },
    cssAnimationProp = { fg = colors.cyan },
    cssUIProp = { fg = colors.yellow },
    cssTransformProp = { fg = colors.cyan },
    cssTransitionProp = { fg = colors.cyan },
    cssPrintProp = { fg = colors.cyan },
    cssPositioningProp = { fg = colors.yellow },
    cssBoxProp = { fg = colors.cyan },
    cssFontDescriptorProp = { fg = colors.cyan },
    cssFlexibleBoxProp = { fg = colors.cyan },
    cssBorderOutlineProp = { fg = colors.cyan },
    cssBackgroundProp = { fg = colors.cyan },
    cssMarginProp = { fg = colors.cyan },
    cssListProp = { fg = colors.cyan },
    cssTableProp = { fg = colors.cyan },
    cssFontProp = { fg = colors.cyan },
    cssPaddingProp = { fg = colors.cyan },
    cssDimensionProp = { fg = colors.cyan },
    cssRenderProp = { fg = colors.cyan },
    cssColorProp = { fg = colors.cyan },
    cssGeneratedContentProp = { fg = colors.cyan },
    javaScriptBraces = { fg = colors.fg1 },
    javaScriptFunction = { fg = colors.cyan },
    javaScriptIdentifier = { fg = colors.red },
    javaScriptMember = { fg = colors.blue },
    javaScriptNumber = { fg = colors.magenta },
    javaScriptNull = { fg = colors.magenta },
    javaScriptParens = { fg = colors.fg3 },
    typescriptReserved = { fg = colors.cyan },
    typescriptLabel = { fg = colors.cyan },
    typescriptFuncKeyword = { fg = colors.cyan },
    typescriptIdentifier = { fg = colors.orange },
    typescriptBraces = { fg = colors.fg1 },
    typescriptEndColons = { fg = colors.fg1 },
    typescriptDOMObjects = { fg = colors.fg1 },
    typescriptAjaxMethods = { fg = colors.fg1 },
    typescriptLogicSymbols = { fg = colors.fg1 },
    typescriptDocSeeTag = { link = "Comment" },
    typescriptDocParam = { link = "Comment" },
    typescriptDocTags = { link = "Comment" },
    typescriptGlobalObjects = { fg = colors.fg1 },
    typescriptParens = { fg = colors.fg3 },
    typescriptOpSymbols = { fg = colors.fg3 },
    typescriptHtmlElemProperties = { fg = colors.fg1 },
    typescriptNull = { fg = colors.magenta },
    typescriptInterpolationDelimiter = { fg = colors.cyan },
    pythonBuiltin = { fg = colors.orange },
    pythonBuiltinObj = { fg = colors.orange },
    pythonBuiltinFunc = { fg = colors.orange },
    pythonFunction = { fg = colors.cyan },
    pythonDecorator = { fg = colors.red },
    pythonInclude = { fg = colors.blue },
    pythonImport = { fg = colors.blue },
    pythonRun = { fg = colors.blue },
    pythonCoding = { fg = colors.blue },
    pythonOperator = { fg = colors.red },
    pythonException = { fg = colors.red },
    pythonExceptions = { fg = colors.magenta },
    pythonBoolean = { fg = colors.magenta },
    pythonDot = { fg = colors.fg3 },
    pythonConditional = { fg = colors.red },
    pythonRepeat = { fg = colors.red },
    pythonDottedName = { fg = colors.green, bold = true },
    clojureKeyword = { fg = colors.blue },
    clojureCond = { fg = colors.orange },
    clojureSpecial = { fg = colors.orange },
    clojureDefine = { fg = colors.orange },
    clojureFunc = { fg = colors.yellow },
    clojureRepeat = { fg = colors.yellow },
    clojureCharacter = { fg = colors.cyan },
    clojureStringEscape = { fg = colors.cyan },
    clojureException = { fg = colors.red },
    clojureRegexp = { fg = colors.cyan },
    clojureRegexpEscape = { fg = colors.cyan },
    clojureRegexpCharClass = { fg = colors.fg3, bold = true },
    clojureRegexpMod = { link = "clojureRegexpCharClass" },
    clojureRegexpQuantifier = { link = "clojureRegexpCharClass" },
    clojureParen = { fg = colors.fg3 },
    clojureAnonArg = { fg = colors.yellow },
    clojureVariable = { fg = colors.blue },
    clojureMacro = { fg = colors.orange },
    clojureMeta = { fg = colors.yellow },
    clojureDeref = { fg = colors.yellow },
    clojureQuote = { fg = colors.yellow },
    clojureUnquote = { fg = colors.yellow },
    cOperator = { fg = colors.magenta },
    cppOperator = { fg = colors.magenta },
    cStructure = { fg = colors.orange },
    purescriptModuleKeyword = { fg = colors.cyan },
    purescriptModuleName = { fg = colors.fg1 },
    purescriptWhere = { fg = colors.cyan },
    purescriptDelimiter = { fg = colors.fg4 },
    purescriptType = { fg = colors.fg1 },
    purescriptImportKeyword = { fg = colors.cyan },
    purescriptHidingKeyword = { fg = colors.cyan },
    purescriptAsKeyword = { fg = colors.cyan },
    purescriptStructure = { fg = colors.cyan },
    purescriptOperator = { fg = colors.blue },
    purescriptTypeVar = { fg = colors.fg1 },
    purescriptConstructor = { fg = colors.fg1 },
    purescriptFunction = { fg = colors.fg1 },
    purescriptConditional = { fg = colors.orange },
    purescriptBacktick = { fg = colors.orange },
    coffeeExtendedOp = { fg = colors.fg3 },
    coffeeSpecialOp = { fg = colors.fg3 },
    coffeeCurly = { fg = colors.orange },
    coffeeParen = { fg = colors.fg3 },
    coffeeBracket = { fg = colors.orange },
    rubyStringDelimiter = { fg = colors.green },
    rubyInterpolationDelimiter = { fg = colors.cyan },
    rubyDefinedOperator = { link = "Keyword" },
    objcTypeModifier = { fg = colors.red },
    objcDirective = { fg = colors.blue },
    goDirective = { fg = colors.cyan },
    goConstants = { fg = colors.magenta },
    goDeclaration = { fg = colors.red },
    goDeclType = { fg = colors.blue },
    goBuiltins = { fg = colors.orange },
    luaIn = { fg = colors.red },
    luaFunction = { fg = colors.cyan },
    luaTable = { fg = colors.orange },
    moonSpecialOp = { fg = colors.fg3 },
    moonExtendedOp = { fg = colors.fg3 },
    moonFunction = { fg = colors.fg3 },
    moonObject = { fg = colors.yellow },
    javaAnnotation = { fg = colors.blue },
    javaDocTags = { fg = colors.cyan },
    javaCommentTitle = { link = "Comment" },
    javaParen = { fg = colors.fg3 },
    javaParen1 = { fg = colors.fg3 },
    javaParen2 = { fg = colors.fg3 },
    javaParen3 = { fg = colors.fg3 },
    javaParen4 = { fg = colors.fg3 },
    javaParen5 = { fg = colors.fg3 },
    javaOperator = { fg = colors.orange },
    javaVarArg = { fg = colors.green },
    elixirDocString = { link = "Comment" },
    elixirStringDelimiter = { fg = colors.green },
    elixirInterpolationDelimiter = { fg = colors.cyan },
    elixirModuleDeclaration = { fg = colors.yellow },
    scalaNameDefinition = { fg = colors.fg1 },
    scalaCaseFollowing = { fg = colors.fg1 },
    scalaCapitalWord = { fg = colors.fg1 },
    scalaTypeExtension = { fg = colors.fg1 },
    scalaKeyword = { fg = colors.red },
    scalaKeywordModifier = { fg = colors.red },
    scalaSpecial = { fg = colors.cyan },
    scalaOperator = { fg = colors.fg1 },
    scalaTypeDeclaration = { fg = colors.yellow },
    scalaTypeTypePostDeclaration = { fg = colors.yellow },
    scalaInstanceDeclaration = { fg = colors.fg1 },
    scalaInterpolation = { fg = colors.cyan },
    markdownItalic = { fg = colors.fg3, italic = true },
    markdownBold = { fg = colors.fg3, bold = true },
    markdownBoldItalic = { fg = colors.fg3, bold = true, italic = true },
    markdownH1 = { fg = colors.green, bold = true },
    markdownH2 = { fg = colors.green, bold = true },
    markdownH3 = { fg = colors.yellow, bold = true },
    markdownH4 = { fg = colors.yellow, bold = true },
    markdownH5 = { fg = colors.yellow },
    markdownH6 = { fg = colors.yellow },
    markdownCode = { fg = colors.cyan },
    markdownCodeBlock = { fg = colors.cyan },
    markdownCodeDelimiter = { fg = colors.cyan },
    markdownBlockquote = { fg = colors.fg4 },
    markdownListMarker = { fg = colors.fg4 },
    markdownOrderedListMarker = { fg = colors.fg4 },
    markdownRule = { fg = colors.fg4 },
    markdownHeadingRule = { fg = colors.fg4 },
    markdownUrlDelimiter = { fg = colors.fg3 },
    markdownLinkDelimiter = { fg = colors.fg3 },
    markdownLinkTextDelimiter = { fg = colors.fg3 },
    markdownHeadingDelimiter = { fg = colors.orange },
    markdownUrl = { fg = colors.magenta },
    markdownUrlTitleDelimiter = { fg = colors.green },
    markdownLinkText = { fg = colors.fg4, underline = true },
    markdownIdDeclaration = { link = "markdownLinkText" },
    haskellType = { fg = colors.blue },
    haskellIdentifier = { fg = colors.cyan },
    haskellSeparator = { fg = colors.fg4 },
    haskellDelimiter = { fg = colors.orange },
    haskellOperators = { fg = colors.magenta },
    haskellBacktick = { fg = colors.orange },
    haskellStatement = { fg = colors.magenta },
    haskellConditional = { fg = colors.magenta },
    haskellLet = { fg = colors.red },
    haskellDefault = { fg = colors.red },
    haskellWhere = { fg = colors.red },
    haskellBottom = { fg = colors.red, bold = true },
    haskellImportKeywords = { fg = colors.magenta, bold = true },
    haskellDeclKeyword = { fg = colors.orange },
    haskellDecl = { fg = colors.orange },
    haskellDeriving = { fg = colors.magenta },
    haskellAssocType = { fg = colors.cyan },
    haskellNumber = { fg = colors.cyan },
    haskellPragma = { fg = colors.red, bold = true },
    haskellTH = { fg = colors.cyan, bold = true },
    haskellForeignKeywords = { fg = colors.green },
    haskellKeyword = { fg = colors.red },
    haskellFloat = { fg = colors.cyan },
    haskellInfix = { fg = colors.magenta },
    haskellQuote = { fg = colors.green, bold = true },
    haskellShebang = { fg = colors.yellow, bold = true },
    haskellLiquid = { fg = colors.magenta, bold = true },
    haskellQuasiQuoted = { fg = colors.blue, bold = true },
    haskellRecursiveDo = { fg = colors.magenta },
    haskellQuotedType = { fg = colors.red },
    haskellPreProc = { fg = colors.fg4 },
    haskellTypeRoles = { fg = colors.red, bold = true },
    haskellTypeForall = { fg = colors.red },
    haskellPatternKeyword = { fg = colors.blue },
    jsonKeyword = { fg = colors.green },
    jsonQuote = { fg = colors.green },
    jsonBraces = { fg = colors.fg1 },
    jsonString = { fg = colors.fg1 },
    mailQuoted1 = { fg = colors.cyan },
    mailQuoted2 = { fg = colors.magenta },
    mailQuoted3 = { fg = colors.yellow },
    mailQuoted4 = { fg = colors.green },
    mailQuoted5 = { fg = colors.red },
    mailQuoted6 = { fg = colors.orange },
    mailSignature = { link = "Comment" },
    csBraces = { fg = colors.fg1 },
    csEndColon = { fg = colors.fg1 },
    csLogicSymbols = { fg = colors.fg1 },
    csParens = { fg = colors.fg3 },
    csOpSymbols = { fg = colors.fg3 },
    csInterpolationDelimiter = { fg = colors.fg3 },
    csInterpolationAlignDel = { fg = colors.cyan, bold = true },
    csInterpolationFormat = { fg = colors.cyan },
    csInterpolationFormatDel = { fg = colors.cyan, bold = true },
    rustSigil = { fg = colors.orange },
    rustEscape = { fg = colors.cyan },
    rustStringContinuation = { fg = colors.cyan },
    rustEnum = { fg = colors.cyan },
    rustStructure = { fg = colors.cyan },
    rustModPathSep = { fg = colors.fg2 },
    rustCommentLineDoc = { link = "Comment" },
    rustDefault = { fg = colors.cyan },
    ocamlOperator = { fg = colors.fg1 },
    ocamlKeyChar = { fg = colors.orange },
    ocamlArrow = { fg = colors.orange },
    ocamlInfixOpKeyword = { fg = colors.red },
    ocamlConstructor = { fg = colors.orange },
  }

  for group, settings in pairs(highlights) do
    vim.api.nvim_set_hl(0, group, settings)
  end

  vim.g.terminal_color_0 = colors.bg1
  vim.g.terminal_color_1 = colors.neutral_red
  vim.g.terminal_color_2 = colors.neutral_green
  vim.g.terminal_color_3 = colors.neutral_yellow
  vim.g.terminal_color_4 = colors.neutral_blue
  vim.g.terminal_color_5 = colors.neutral_magenta
  vim.g.terminal_color_6 = colors.neutral_cyan
  vim.g.terminal_color_7 = colors.fg2

  vim.g.terminal_color_8 = colors.gray
  vim.g.terminal_color_9 = colors.red
  vim.g.terminal_color_10 = colors.green
  vim.g.terminal_color_11 = colors.yellow
  vim.g.terminal_color_12 = colors.blue
  vim.g.terminal_color_13 = colors.magenta
  vim.g.terminal_color_14 = colors.cyan
  vim.g.terminal_color_15 = colors.fg0
end

M.update = function()
  local dir_path = os.getenv("TINTED_DIR")
  if not dir_path then
    return
  end

  local theme = io.open(vim.fn.expand(dir_path) .. "/theme", "r")
  if not theme then
    return
  end

  vim.o.background = theme:read("*all"):gsub("%s+", "")
  theme:close()

  local palette = vim.fn.expand(dir_path) .. "/palette.lua"
  local ok, colors = pcall(dofile, palette)

  if ok and colors then
    M.apply(colors)
  end
end

return M
