vpn:
    pk: ENC[AES256_GCM,data:Pz5uxxTQnmal3g/8E9dJ1TTgEWLy+9QrxK0pB4qAjFKbk8SS3uJj0XpgGHg=,iv:Xvbas+v071E1UwFpzAxmFc5b4Vxr2Yeg2ArVjByS87Q=,tag:ZDdIR6Mq7fMVNlX1TUcHqQ==,type:str]
kdeconnect:
    key: ENC[AES256_GCM,data:xLb9yb0Aa13SISwOfBK7YrG1F+pLWzbFOkRdHRBzXBspgGCr0Upa6y+tUmlZEt0PEAgmRQjjXyccviOSM/SW3rufocHTNuPPNnJCsKZ/j8F2yaPuOm+a+kmTQM58u8Jm5uWhrjJEOIfCGswbXznUYriQvUaFj21l8MKcURQtv0243G8tmH316bE+dQFf2UWVh36z3eGjEBW2paDwhzLcvGF5v1yiEsFrB3mjWTf6yNXMJyyEkrqWv2jCh8vEvn1oIsphMNLcF7tXsBqAS5y+gCLon8BXaS6N2X/bdooqp4GL+PM=,iv:sKQj+Jv1KkHnKZEJ2J9UNvgOR2L9WlW+YtBLO8Pp1Qc=,tag:l+NrZQol367p/ZzbyW6QMA==,type:str]
syncthing:
    key: ENC[AES256_GCM,data:A4Ptr84iAgevfb9YX3dQJB03C4hbhLZvMt8SlGSmZgFKjJ1yCPGLXkYjFLRU9ngYORpfGrhE7/dNqUaQzoRuE6dN4J4ymrClcQ9ymWZOA3ARkmHkr8q91nxyzND4amNzRoAcVzG0oM9PPh5eIWpI+REAJOkF/Po=,iv:uRxfCdCqIrFq/pzyYoaSHqIcHmTxzoBt2VE0F5mcMPc=,tag:E7FtwxVB2PMU4nP2rTs3uw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IEhDRzNuU3FE
            TmZXTVlpcElNVGNuM296ZWRMMjhFTkl0SmVNbkxnS0d0OGVrVzhMR04rQ1pxRlJS
            T1FETkt5bGVkVlp6N3NPa0tZRmxzNHMwcGwrVkNsMklOcWZNTmNWZzQ1eEpHaGxl
            NktEQm1Gb2V4TC9LNDZYTEJWQ2UzRkE0cmxOUGNzeXlGSDZnNWxvR08vcGhCNWxK
            ZlRpZXQ3YXI0OWRpdTNORHpUTERKS2pkRzdXbmlDRVFDbFVSSlFSWm5xQVhZMFhk
            ZFhPcHVlVlUwRGlqNkEweFZjM1FCRDI5VUphbEtjREYzbjZGUlFoM2o5RlJXS1Nn
            STh1ZEFNSy9GTGZGVzVldUhBZTFtV0VvK3NheFN0bUs4N1ZCbEliRVd6dnRjNnVx
            ZGNqV1ZtQ2ZrUENQVkFYT0lxRU5TSFR2cjdXWVN1YzdUbXZQZkQwcGp0L2JBbStD
            bXhxUFpXVUJMZFJ1bFNGUm5UTVQvU28wd3RVQjNtcUVOOFBaU014dldrYVdmNDVy
            NVNESmF1d1MrQytNMVlWV2t5a0todHMrOVYvVnk0RVpDbnNWTnluaW9KSnh4UHdW
            MkJUNEUvM0w4akFkL0o3QXc2aCtwTWUyMUNDNzZuKzFKaC9UNzFzVjhnYUZLRm4v
            U09sbUtGRWw1dUxJVW93eEVIMjFqcS9VT0tFSitIWXdEbnBzUEpLT3RUOWhhTTls
            NnVTVGR5eGloTlA4Qldya3Z1eWRFVnh1OGxqTFJxdmM2QjkzTWRlV1lwRkV6QXlM
            TXkwekNUU1oxOTJibG80bHRhVVgxcFQrMENoODcreW4yeHlLTmhHbUlZaGIwVitK
            ZU1MTmVrK3g0R0xORW1uVnpqeUR2YmRQTDJyTDFSdHdjRkUrVUtVdkJhMHpad1RJ
            ZjJRZm5ESnBTYlU4SE9tY25XbjdNREVJSkoybGtGL09yaStaOEV6dno1ZEVORW4w
            TG9uaENTU0RlM29BWmx1RFZDbEFnMitYMzBlS2dqUXZrdkptMGRmZ1ArelFnbndE
            bWs0R3lYQmNkelZIWVZCVFk5d3oyNWY3VkdUak9IbFc4RDdnMDB0aklITTdPMWl1
            TmdrV2FBZUpwRENmLzU5Z3hFdnlsZ2lkMTh2Y2QwSDRnUWcwdFdUaGhOa2pPK25j
            dHRMSm9PK05XWHU4UFVNS1p1LzZ5blhGdFhkUHhsclVpMTVQSGtQK21Fd05raU9V
            QmU0WXlFS2JpQzAvMnNjTWJGOTFPdVo2dFJxMjV6Z2lXd0VkR2xKclJGQUdkK0Nj
            Vndac1pqT25wN3JhVmlydWhnTDBJVFQ5a1lWUThmTTd2Wm9ZZlVBNWFUOHpTWEJW
            dUd2RlhLQUNQbkxxRTJHOEtOTlFDdHpjOFgydmNMK1N2bXcrQTg2UU9McnZUVW1s
            QlVtZDJzWmJHQnl5c005eGZPTDJQSG1MRGV6UVluek1kQVZzTDVTditZY1FNYlIz
            a2ZyN2U1dUJIQ3NLcFBtRUMxQXNuWkhIWW5wVWVKenBrVm96NjlzVnFuV1pVOGVl
            VHBLQ0RNdHF6R3c4TkdCaUZZSTVpSUxKZXZQaGc4K2VrWjU0VG1WUWNDVkk5SzJa
            RUgxWUZLdEJvWCtyU2w3V3VhQ3JqbUxBc0JOY0xrZk9IY3ZnTEo1eXBEWjM5Q1V0
            dmVLckhneUk2cjAzazEzUnVsemphTjhkRHdVcUFPcVZoSHpKbnJnWjM1S3Q5eXlU
            dzExZXZSN25oTktHZ0g5dmNmUmkrMjMyZkNTSlBTcXZ6aHRSMHh0Q0lqMjV4S0ZG
            bGpSMExuZmVCTHVqVGI5T3cwaTdpcXNWWHp0MEFOV1ljekkyd0wxQTdnZ0lVaHlC
            YnpsbjFOSERHVWNSVmgyWVg4QjM0dXZ5NTdwY01LR0VWdjFEdWw0enQ0TVM4K0Fj
            aEJTL1g5NWt5R2h3N1d5NVJYS2dvd2JzVkRoTUl6NnV6ZWpvYVJ1dkVMSVZXQQpu
            b1VOQWlzMlpHTzhvalFzRGZROWkxZ3ZWREsxUm1KSW9peHBseHpwN3B3Ci0tLSBk
            bG9EM1Q2d0lyenZoZnFmSmswNXVIRkZ5MjA2OUJJRFhqUFZJMUdBbnRjCqs8L69R
            8cf+VkediR2Jx1ktuUmk4BrGlIxGy8a0GoaKUmI0JRzLoHguqV2nIwCn42DqKKtI
            BENi0hJmX4je95k=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq15zkgrl6kqmch899ejsehzdqvyudyz33uq65njscappkvfqm4tqermjgud0rddvq4rpryr5r5jx35c844fsr7245k72jtd755tdqmt6jgv84pt2g6kz0plkugknvr6s84x5f9s906qdlrwsmjveyu3egvv8mxhvfxhxtpw9qqvwmt7uf8jtk6sq7xgk49yau46ufr8qf2q05ycjyxvf57hpsrvlr2ylj3jg6j59uknsc8xsexvfrmwaar02w43wdfdwjz6x2pklycp5fr4za4zm3s0scyz5u00nrpgrr2sqwqn03xusjredazgsy5qrwjgy6jk06rhxp7cxs86w4h0gqtpewmes8yk5lhfjdajwucv8tr2nh049vtas8r5yplykjt96u2pm405wmuk3zrkgc2lwm5jnq222ur5vc3aqlee6qpdkdne69tcr7jv4j9vfwppzqnzwanane3qmd2dtvgc9nxugxz0z4m0mexrwtmt00vxqena4cteafexcumhe2q3sfqwzml674gt3p66xpx29hg03yhpqx372axnungrkqxcn5qtz58rqaqe79cgpu9pnkmdl2x24uyxv7l4au5ksgy64jpdq9df8m4nga3x3ya6qnpddgt9wph26g4wzv6sqs4qk9h68hjsdm4gc64u9cscvuakemx0sx9gke7pxwwwjulj5jednz63rcsq2hdnpdvcycfv74q6jgves8xnd6wxyx3j37a7m9hs4ezehkfj0mt240qza80u59x0e4j6c8sk7gwxkvwxw5fs2vzu9yvvnk4y2cckceww8pm5ygjp7fse2zsgl3hvrlyklrw5a9f3td4ynsufj3zx8q5k676gt9ggdnr2jy3pvp6qs7hgmqfc2j0n5kxzk2xxg292p7tsh88h3g9uy526wdps3tmzprvycwagk3xz6s6s67sv0rkf94axasegfrfd02cwvfn3ag0ej2my9f882rly5tfpsw4f27fxqm9qqsxzxtgdt69qxs2p2z699q9keu3ak3h8vu9k6av83dsn8pqk6qs343fyfyvmmhrfdrtf9uujerwapvc85n2cj0s4l0cts03ts2d3u4kah53kvl8r5clt9gsckcdnuuj9a428s463gqlcxlkwq2vp2p0qctcepzzykezclvvuf3x04av0da3t32mq2mztv96eppakknczh94hrved7ya276s9t97wxn7tn9m83c945zhz49yseu4k76lcmfesudc2u9hd9azshxzc2d90zee03lhqrltj5xgs7dlpm9d25j9avfzg25v0zw4zzdxm2att6gmu3d5zeaaj9zv3vw28wvp8pdzmq9k5r348th5l0qv2jrgx5y3qfpndzvuz34uz3fkk3vdky32g7yesg2scuf7kgr2uszf925333g3kgjp4x396fns4wzhlap6slfh537qqlxwdgv05u4kaff9hwtpp0hzp2ks0g3hpvugm5u8h3scdq08yxyxa9esm2fnf3sgterqxy8kjaxzcyd48evlehnsss4e34v89s3sy4qa5q2qh5jz7sykjmha5enke9hpdry6d5k9us7h2d5szklegwfkgz48krs5epfc0kz7dfjvqw85m8r0x84kejge4huesztw0yrarw9x3ug99uh2qd7y5lkw0v8e069ptd29pmhshehngt5zu625aftxf7crawgkzeckz5hhdqq6jd5ftqzcupme0nzhql3c4s3cn5gl58muqrnjj45qfvlfaz5xc5d9znpu2dfec5v5qz0mlrq4ehyltj3gdnrn8893vmmuhty686z8u8jxzrlgj3em80rfazqwqhnscnh8x2qlwhs8f0u044fjh4h73e862fe9xg8cwqu2f290tc8mgedckg5tj7mdwz2nfkkl7t3yxmx7ukza3xwhauqpt3s7vzdezyqx9tqv
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IG1sa2VtNzY4eDI1NTE5IGpSVDBHWXkz
            UXB5d3hGT0JDM2ZNVTgxYVE2eEhHNGVnbmd2dUtPRDczQVdoQjk0WVdyTCtIZXg5
            alVRTWp2VEZxczlQakJjQVU3WXJ3WXNvVlBmSUpCK1h3cS8rVEd2ei9ZblVxM0pq
            SkFDNU5SOW9YQjE1Y3lMK0hiTzhlUVNESmZBWDlEMnJxUGMrNjRRa2V1QzE4YVo2
            N2hGL0xFcGZ1Q2hIdC9pWXFCQWZvenNMMWQ5Rnh3TmVTM0NmZXFrM1JvcnJoWDN0
            dzFxc1NWdXdIUENMbEpVazBwQWEwem1MbUxlZmNFWXJnTVJXZS9ocTRuZitkd2Fz
            cUUwVVc2bTdPZXBpbGRIQzhvZlpSVU5HL202SFFDU1FZcFRUNnlpa2YxVWdoelBt
            Yi9zODBuUGNacDhXc0ZKY0FHcmJUUTlsM1ZQYm5NR21FYm5xcjZNTVdZNUk5U0Uz
            WGtEU1JiRllUT2U3UnBmbFB6OTFldEFFZVJBYnZoS1JwMkhKZmg4TGtzNThnMlky
            MFZ3andmNTlxWDlRbHlaaTZXQmV3SHV1eXAwdUx2ZkZIRlE4OEszbjNYZkpNYVZO
            YXY4Z00xdHR4bG5wRlFHdXhXY1FIRm4zNG5td1dLK3dESlQ3WnptR3NzUTNYWlkz
            NUxHMVN3QTJoVlpqdGVyd1F2Y24yZE9WK1NxeWMxeEx1UkcyazA3eUdzNS9UUzY5
            VjdmMnoycU9ySzhDYzFsdHZwVWlGMHRYODFSbExYQ0NUZ1RPNFc0YVg1V0haVm50
            ZlgxRzZMOGgyaDJFVkFpcDF5cndBbnVFVWgwUm00ZldJdGozVzFyMW4rbmIwRHlr
            SmJ0WHFGSTUxdzg1cXZKRzVYaWhsTnVyelpxalRBNmIvMThUZXc4blBIWjFWanRl
            YUhWRk1ZTEgxNndRbEhScnNmRFRzaFZQZmRwMFE0dWNkQ2VQYlZYdjcwUzhjaFA2
            OUw5RGR6T1BpclljZWpmT3VDSlNsS2p1ZjJqdWsyOS96THl6Tm04RlhUaXdOeCtl
            aVF1Z1V4eCszOFZaRXpUN04wVHpNMkNSMUZleXlCRytrNXBMajFkaDBQNEk3VXor
            YlFsWTRKc29KQmQ5aGxqYklUU1VETXBKanpkc0lYOXhXTnllaUVEODlTWnlUR1hp
            YmhVMHhET3h0OFRPN0s3YVdvb2FIMHlnRjBZaVg2Z0JOWEk3Vkd6YXhhWTUyVkov
            VjloMnRtaTZMUHRsK25OVWlRYWN0UTJYaHNWU1pZS3NxSTRaRXVqaGkwZCthUis5
            VjNxenBKM2p6ZmR1ditaR1d0UU50ZmF6RThLNUNBWHRWekdyUG1EUlROWVZqQ21L
            NXFldWwxeGdVeWEvdG1VMWlCTlhob25heEhzMi9YNTBiTFhGcHVFaUtaOG1lUHdr
            WFJLVCtMcENzWWgremJYL05nbEJXTEozUis1RDNPS1kzNE1YRzZtbEFlaVQ2V1Zv
            MXhSV1V6ZEZ0N1QzQ2tLakt0cXZ6Ny9hT3BkL21GcXdDbHNGMTJCT1VwYlp4TnBT
            bXdWaUZKeGZDakpncmRONmdUOUhNRDJ6dkwzTFF2SmtMQkJFVDFOZzVjcFh1UFVs
            SjJ5RnVKNzBrNTQxVnVRSGdNSzhkMW9JTVpiWklBdzBFUXVjOHc4MGV2eWRtN1pY
            dFhYZHpIMXlyMXZmS0w3TnBVNGFhc1ZmTlhFeG9PWFkvZ08xemJyU1VpS0xYUHox
            a1VCRGFnRHRCNUVsRUlIeUc5cmZkWnBrdStKVEJWZy9HSnNyMzQ0M2ZkODhDWTJS
            ZWhXeWpNZ05YamxqT0p0Qlp0ZERIRWFsYlFiSmppVnFkQ2kvQ2krOGtIOXJ3M0xw
            RmtyaEdLR2VmaTYyWnBtR1RBQ0h6NkFDVDQxYXlSNFZRT2hXdWZEMitXSU1KY00x
            TDFYWVhaV2pjWTV4RmJmZkQ5WmJnazlMWEJXSWg0Y1RxdHJkdFhqVktuaHJEUQpX
            NDlGdUF6SHVEeEhpaUY2bjRyOGRPOHVyNUNFYzRKWDFoUWdGVGp3NkRjCi0tLSBq
            Q3RTMW9XWExZYnQxbzE5M2NheGZRanN0MFVBb3RzbHlCM1FVcFlYVTUwCtAXQXeD
            FbGWcLdAjvPccv/rhnWXcnyBaNVYR9Mvt1D527LjV1s+UAm/owDJtH+cb6o6U9AR
            ZB8wl5hEY9PGN9c=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1pq1xme50rm3zwqyzhqpjx078eandu987n4n2n6h0g7ludxlfvml4enydqkfjjhkrny0zs6k699076r5n36cjm76c582wk99kfqk8rmr0vsgswlkwlj5tdf0kgxpmr38c34n0pass6kxh9kc62zz8w6u65hcxlwjn0mahx6wqx6xnxpyve25n3qn3qh43f3vlufkrq6ftjt6833uvvkst9y3usyqlvpesj55vn3uwmqmuynsx7wzztgh7qsqz4z2f3unrx2spc935ade7t785rhafgdwpyj59xgf0zj4phsrrwmagzgwhzut9cdsjd44wu8fszahtn8hrf8gaztxz0xyc4khsd6leys2jfysglq98hcn4cchd8lu9wffjsyxt3e9gae8630n20c60g0pygar2jk8u0494d3f85rqg4e2fyq8ver8dut3p9c8rvvrgdy99q23qjfcvddt9canthzxr2jgz8p9khrj5zw2hrksh6r7y63jy94pn3uvwtk8xv09z2cgr0nhjaqp7azqraz2lu55x7ndfpa4sjpftczxe843r9u3pvu0tz5dy9pmgk2tm4dzy8qkgv8y4jlawxxf6fk8lwfk864hkf9ytsxnwg00evy2qf29938xyhkf3qurusuvysr8qws946sfpj7efv9c6px55qjlrp2ggu2vjqfkq0gk79nqf3ec2yy2u86t2yyddqq7yw33g2gygdgzw9h65w9q5zg9xg5m4sfe9rq29m7hp2p5yy4lge0wuetv0dyqvhwvylm6nfrm3skpuu4g78ffcp5mr8lq5nhvfwgjxfyrz0qma8lqqndwcjknhf5nfsj22p98qdmf0qdcfqy4y3zpf4jqzg6f02as24f8pjcns9pzfvyrvjrv87ujjpx2gvnhqgj7zjm2ywqpuusfq3zrguw96vrsm3j27r68spqht0cgr0stxu670cduv2cjahxs3w4y02xh6frnrj3a66rm9s9vn4dj4ygtnzajeqpyapsnqn5t8ag72sgwx6lj02vemskvkpytx5jwz2fpj9qze9qzcdextefvzslgf8qz6pystcy6aaz2zqevkdtz3pe0a9shqktzkmtxkhunrc4qx7fgjdexqc9rd6tnvf4xnyzjqzu5efwv0wdn4z6nh4gh2wf0xlzlzwm5jq4ce3sf3u24e888fp07vxqes5m5e8enue6x9j26w0wxqxfvtdtc9qr6zmcsrrd2np8rd33tq7s9k9ty9lyq4fkle3lyuugz5fkqgjgrqtcmesqeyxhwqu4elf6p4zqe46fqd4xhyy2cj9f2vwjde7eqd4xgr665dynk8xxvt9k2wwvmjh5zxqscql7ru46rpdpf4lj4kl68gdrr5tgt8s4mdy5gzeux797yf58qvmf96p67ne3fpdg4972hguxtvgfxxcu6pry2zxpe659hvaz0yzcdf92nfw4x6vp822dfdjy3w4ckq9hvuyf6xcrqa8g6pfmygtdcuqtuwqu5wx3y0dvg83umg3uv2pftu9cuqvwy3tmmtdgjzaj4z5za82qc049xyfps3zse8yajuzqrxv5mlyse2l0zj0k8rw5569f77ynvsupmffxmg3f5gm2uv4vt2e9t7wcjwxerqug8vjjwcwx932eu60p3ygd297m69853qs622ztkr7ttldm3zxw9jhcxya9444y0znn6qhc8qs8czq39x9f7e6d83xs5sk06zk65g00n0vedz39c572nuu7q4u3k5xnrcd52z3rygycym4wuqnnhx8xeyj6c8am7tmr38uzc400hyz5q92xtp3aualuz0ec40qhuw8ur4fy36pq23e9udw22ampdm8slvue5dg96m09zk3vhzhykhatc5qu2ps3sapzfmv6qt9v2u7fwaw2gktpvxvuaclpy0dqjck0mhuysmexqpsq899xz
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE8zUXdoUSBBdE9VQ0JP
            ajNVazhvRVVnU1dTbmE3TTJGS3lTREdQRjNUczBqdG9UeWhlRgp6Q3NQSmoyWUtt
            b3pWbUNRMXlpTmxJUDBVak93VVp2WW5DVzFTUU9SbHlNCi0tLSBQb0NIYi90ME5D
            MzJVYXRKL2tDUnRJdGg5cVR1TUdsRnFuSStxNU1GUXVVCpdJ0UnRkBVZ78Yi+yyU
            1g9XGb/kFbv5eyWpvsUm8PmFz9lDeMZWBHxDePyfIm0F6R3ZHgGdfJ1apCSEl/sK
            LYg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qwrp2meyq50afmrydcq7ejfwh9hj6zxfwg5wmgg5q5eudavd090v7urw3d5
    lastmodified: "2026-04-16T17:28:25Z"
    mac: ENC[AES256_GCM,data:78YsEiJIHxq7vu8qVneEqTyeEZS5bSOui/RpokQrdxTZBRLeoj8WbF9pGKAYT2zmL+mPRKspCfRlFx3saekhd2KvpB9+blNW8fGQ8fNxzmqbLuj27JWzu8gYX2AwCoUMUBkEt8fCY2Gm+Te1EljBQrzY4Rq85t4rI59kiaFWt/4=,iv:ObogtTwPCSvrqKXp6J8oGwDQywXJpDFrWT8Vy3uf+jA=,tag:fkzA7GtOFmVeAXt57ztuWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
