vpn:
    pk: ENC[AES256_GCM,data:Pz5uxxTQnmal3g/8E9dJ1TTgEWLy+9QrxK0pB4qAjFKbk8SS3uJj0XpgGHg=,iv:Xvbas+v071E1UwFpzAxmFc5b4Vxr2Yeg2ArVjByS87Q=,tag:ZDdIR6Mq7fMVNlX1TUcHqQ==,type:str]
kdeconnect:
    key: ENC[AES256_GCM,data:xLb9yb0Aa13SISwOfBK7YrG1F+pLWzbFOkRdHRBzXBspgGCr0Upa6y+tUmlZEt0PEAgmRQjjXyccviOSM/SW3rufocHTNuPPNnJCsKZ/j8F2yaPuOm+a+kmTQM58u8Jm5uWhrjJEOIfCGswbXznUYriQvUaFj21l8MKcURQtv0243G8tmH316bE+dQFf2UWVh36z3eGjEBW2paDwhzLcvGF5v1yiEsFrB3mjWTf6yNXMJyyEkrqWv2jCh8vEvn1oIsphMNLcF7tXsBqAS5y+gCLon8BXaS6N2X/bdooqp4GL+PM=,iv:sKQj+Jv1KkHnKZEJ2J9UNvgOR2L9WlW+YtBLO8Pp1Qc=,tag:l+NrZQol367p/ZzbyW6QMA==,type:str]
syncthing:
    key: ENC[AES256_GCM,data:A4Ptr84iAgevfb9YX3dQJB03C4hbhLZvMt8SlGSmZgFKjJ1yCPGLXkYjFLRU9ngYORpfGrhE7/dNqUaQzoRuE6dN4J4ymrClcQ9ymWZOA3ARkmHkr8q91nxyzND4amNzRoAcVzG0oM9PPh5eIWpI+REAJOkF/Po=,iv:uRxfCdCqIrFq/pzyYoaSHqIcHmTxzoBt2VE0F5mcMPc=,tag:E7FtwxVB2PMU4nP2rTs3uw==,type:str]
sops:
    age:
        - recipient: age1zmpz7zl6hjrqarz4w5lsnkrqw66e63np08pdt8c5rrdh70etlqwq03ksp7
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJUTFrQXdQcWhEUFhYbTNz
            bXFoOUJYbzYwVmlTWG5rWHcwaUgxbjEvVnpJCmRycWI1b0R5QjU3Qk9iZXh5OUNh
            cVR5QWpxdjdodkVBVEpLVGhOcWZVcGcKLS0tIGZmVnZxVnNsQU8rRVdleEFGM1A4
            SXNiWENtN1NzQ3Y5b3dTdWkrNmJTczQKXazEh91BhpumFBnXJTstxAM05YtSL1f8
            xVtTdUCbTO/p+VOTB65V1cG2DmrGdxQNH7thhcjplL5/gGXMLAZ2/A==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1n4q00k9aas6g7eexc7spv32j02m3wez2gcnucre0tx76swazv36q8qchnq
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0SVkxT0dOSk53ZFZrVFFx
            c1Fnd0lrMjAzdEV1czlVc1VaaWhhbGtJUHk4ClBtU1RTdk93LzRvL3RkWTBCYlVr
            T0I4SUl3ZWFhbjF2TUh2VzBZQnp5NTgKLS0tIGpNeEU4bDkxcTJWODRkNWxkSjZz
            aGFuMWZJU1FzNkgyNU42Sjc5a2szNEUK2Lj8BauykrD2rPbBvfLq9amies7wvhr+
            2V5OX8E91ynt5pq1pyBVhcEc3Ca9o4dZMHMLF99jtFx4MfsiphJrAQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1se1qwrp2meyq50afmrydcq7ejfwh9hj6zxfwg5wmgg5q5eudavd090v7urw3d5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE8zUXdoUSBBMVM2SzZq
            NUdJL2FPSjlOOTRtZkIySzFlQUFCalgzTVlwUm91QnRYaWdVZApZU3Zla0p0emJY
            d1E1ZUFNZ3YvemZwdEJmalZuTTc5VmZmL2hkcG5SazBvCi0tLSBtTzhaT2UwWS8v
            MzFQWW9HQ0dBRVN1c3htbndOMFV0MHh1bUd1YkhvbkIwCoImUt/jhspsiq1QdrEG
            LXp9Lw47/oL65VCGv1N6GYWINnokXGzfWLHOoNY74swAK3SW1Amu6OkQJcgP1bBO
            5Sk=
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-16T17:28:25Z"
    mac: ENC[AES256_GCM,data:78YsEiJIHxq7vu8qVneEqTyeEZS5bSOui/RpokQrdxTZBRLeoj8WbF9pGKAYT2zmL+mPRKspCfRlFx3saekhd2KvpB9+blNW8fGQ8fNxzmqbLuj27JWzu8gYX2AwCoUMUBkEt8fCY2Gm+Te1EljBQrzY4Rq85t4rI59kiaFWt/4=,iv:ObogtTwPCSvrqKXp6J8oGwDQywXJpDFrWT8Vy3uf+jA=,tag:fkzA7GtOFmVeAXt57ztuWQ==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
