keys:
  - &yk-main age1zmpz7zl6hjrqarz4w5lsnkrqw66e63np08pdt8c5rrdh70etlqwq03ksp7
  - &yk-backup age1n4q00k9aas6g7eexc7spv32j02m3wez2gcnucre0tx76swazv36q8qchnq

  - &tpm-cray age1tag1qd5s6fcv5upezjgzv4y39t0kfg0tgalwdfmf3elnccu5u87ctzgmxgmt756
  - &tpm-naitoh age1tag1qwdf600uvtxjw58z48lgkg2txky68jhnlrlr0tjdrkl80gqaume6ynnn57f

  - &mach age1se1qwrp2meyq50afmrydcq7ejfwh9hj6zxfwg5wmgg5q5eudavd090v7urw3d5
  - &woz age174yq43fu75xyuf5t92yeekejl6fx84zewy45wqzy538g2qx29clq3gfn3w

creation_rules:
  - path_regex: 'cray/.*$'
    key_groups:
    - age:
      - *yk-main
      - *yk-backup
      - *tpm-cray
  - path_regex: 'naitoh/.*$'
    key_groups:
    - age:
      - *yk-main
      - *yk-backup
      - *tpm-naitoh
  - path_regex: 'mach/.*$'
    key_groups:
    - age:
      - *yk-main
      - *yk-backup
      - *mach
  - path_regex: 'woz/.*$'
    key_groups:
    - age:
      - *yk-main
      - *yk-backup
      - *woz
  - path_regex: '.*$'
    key_groups:
    - age:
      - *yk-main
      - *yk-backup
      - *tpm-cray
      - *tpm-naitoh
      - *mach
      - *woz
