keys:
  - &sk-main age1pq15zkgrl6kqmch899ejsehzdqvyudyz33uq65njscappkvfqm4tqermjgud0rddvq4rpryr5r5jx35c844fsr7245k72jtd755tdqmt6jgv84pt2g6kz0plkugknvr6s84x5f9s906qdlrwsmjveyu3egvv8mxhvfxhxtpw9qqvwmt7uf8jtk6sq7xgk49yau46ufr8qf2q05ycjyxvf57hpsrvlr2ylj3jg6j59uknsc8xsexvfrmwaar02w43wdfdwjz6x2pklycp5fr4za4zm3s0scyz5u00nrpgrr2sqwqn03xusjredazgsy5qrwjgy6jk06rhxp7cxs86w4h0gqtpewmes8yk5lhfjdajwucv8tr2nh049vtas8r5yplykjt96u2pm405wmuk3zrkgc2lwm5jnq222ur5vc3aqlee6qpdkdne69tcr7jv4j9vfwppzqnzwanane3qmd2dtvgc9nxugxz0z4m0mexrwtmt00vxqena4cteafexcumhe2q3sfqwzml674gt3p66xpx29hg03yhpqx372axnungrkqxcn5qtz58rqaqe79cgpu9pnkmdl2x24uyxv7l4au5ksgy64jpdq9df8m4nga3x3ya6qnpddgt9wph26g4wzv6sqs4qk9h68hjsdm4gc64u9cscvuakemx0sx9gke7pxwwwjulj5jednz63rcsq2hdnpdvcycfv74q6jgves8xnd6wxyx3j37a7m9hs4ezehkfj0mt240qza80u59x0e4j6c8sk7gwxkvwxw5fs2vzu9yvvnk4y2cckceww8pm5ygjp7fse2zsgl3hvrlyklrw5a9f3td4ynsufj3zx8q5k676gt9ggdnr2jy3pvp6qs7hgmqfc2j0n5kxzk2xxg292p7tsh88h3g9uy526wdps3tmzprvycwagk3xz6s6s67sv0rkf94axasegfrfd02cwvfn3ag0ej2my9f882rly5tfpsw4f27fxqm9qqsxzxtgdt69qxs2p2z699q9keu3ak3h8vu9k6av83dsn8pqk6qs343fyfyvmmhrfdrtf9uujerwapvc85n2cj0s4l0cts03ts2d3u4kah53kvl8r5clt9gsckcdnuuj9a428s463gqlcxlkwq2vp2p0qctcepzzykezclvvuf3x04av0da3t32mq2mztv96eppakknczh94hrved7ya276s9t97wxn7tn9m83c945zhz49yseu4k76lcmfesudc2u9hd9azshxzc2d90zee03lhqrltj5xgs7dlpm9d25j9avfzg25v0zw4zzdxm2att6gmu3d5zeaaj9zv3vw28wvp8pdzmq9k5r348th5l0qv2jrgx5y3qfpndzvuz34uz3fkk3vdky32g7yesg2scuf7kgr2uszf925333g3kgjp4x396fns4wzhlap6slfh537qqlxwdgv05u4kaff9hwtpp0hzp2ks0g3hpvugm5u8h3scdq08yxyxa9esm2fnf3sgterqxy8kjaxzcyd48evlehnsss4e34v89s3sy4qa5q2qh5jz7sykjmha5enke9hpdry6d5k9us7h2d5szklegwfkgz48krs5epfc0kz7dfjvqw85m8r0x84kejge4huesztw0yrarw9x3ug99uh2qd7y5lkw0v8e069ptd29pmhshehngt5zu625aftxf7crawgkzeckz5hhdqq6jd5ftqzcupme0nzhql3c4s3cn5gl58muqrnjj45qfvlfaz5xc5d9znpu2dfec5v5qz0mlrq4ehyltj3gdnrn8893vmmuhty686z8u8jxzrlgj3em80rfazqwqhnscnh8x2qlwhs8f0u044fjh4h73e862fe9xg8cwqu2f290tc8mgedckg5tj7mdwz2nfkkl7t3yxmx7ukza3xwhauqpt3s7vzdezyqx9tqv
  - &sk-backup age1pq1xme50rm3zwqyzhqpjx078eandu987n4n2n6h0g7ludxlfvml4enydqkfjjhkrny0zs6k699076r5n36cjm76c582wk99kfqk8rmr0vsgswlkwlj5tdf0kgxpmr38c34n0pass6kxh9kc62zz8w6u65hcxlwjn0mahx6wqx6xnxpyve25n3qn3qh43f3vlufkrq6ftjt6833uvvkst9y3usyqlvpesj55vn3uwmqmuynsx7wzztgh7qsqz4z2f3unrx2spc935ade7t785rhafgdwpyj59xgf0zj4phsrrwmagzgwhzut9cdsjd44wu8fszahtn8hrf8gaztxz0xyc4khsd6leys2jfysglq98hcn4cchd8lu9wffjsyxt3e9gae8630n20c60g0pygar2jk8u0494d3f85rqg4e2fyq8ver8dut3p9c8rvvrgdy99q23qjfcvddt9canthzxr2jgz8p9khrj5zw2hrksh6r7y63jy94pn3uvwtk8xv09z2cgr0nhjaqp7azqraz2lu55x7ndfpa4sjpftczxe843r9u3pvu0tz5dy9pmgk2tm4dzy8qkgv8y4jlawxxf6fk8lwfk864hkf9ytsxnwg00evy2qf29938xyhkf3qurusuvysr8qws946sfpj7efv9c6px55qjlrp2ggu2vjqfkq0gk79nqf3ec2yy2u86t2yyddqq7yw33g2gygdgzw9h65w9q5zg9xg5m4sfe9rq29m7hp2p5yy4lge0wuetv0dyqvhwvylm6nfrm3skpuu4g78ffcp5mr8lq5nhvfwgjxfyrz0qma8lqqndwcjknhf5nfsj22p98qdmf0qdcfqy4y3zpf4jqzg6f02as24f8pjcns9pzfvyrvjrv87ujjpx2gvnhqgj7zjm2ywqpuusfq3zrguw96vrsm3j27r68spqht0cgr0stxu670cduv2cjahxs3w4y02xh6frnrj3a66rm9s9vn4dj4ygtnzajeqpyapsnqn5t8ag72sgwx6lj02vemskvkpytx5jwz2fpj9qze9qzcdextefvzslgf8qz6pystcy6aaz2zqevkdtz3pe0a9shqktzkmtxkhunrc4qx7fgjdexqc9rd6tnvf4xnyzjqzu5efwv0wdn4z6nh4gh2wf0xlzlzwm5jq4ce3sf3u24e888fp07vxqes5m5e8enue6x9j26w0wxqxfvtdtc9qr6zmcsrrd2np8rd33tq7s9k9ty9lyq4fkle3lyuugz5fkqgjgrqtcmesqeyxhwqu4elf6p4zqe46fqd4xhyy2cj9f2vwjde7eqd4xgr665dynk8xxvt9k2wwvmjh5zxqscql7ru46rpdpf4lj4kl68gdrr5tgt8s4mdy5gzeux797yf58qvmf96p67ne3fpdg4972hguxtvgfxxcu6pry2zxpe659hvaz0yzcdf92nfw4x6vp822dfdjy3w4ckq9hvuyf6xcrqa8g6pfmygtdcuqtuwqu5wx3y0dvg83umg3uv2pftu9cuqvwy3tmmtdgjzaj4z5za82qc049xyfps3zse8yajuzqrxv5mlyse2l0zj0k8rw5569f77ynvsupmffxmg3f5gm2uv4vt2e9t7wcjwxerqug8vjjwcwx932eu60p3ygd297m69853qs622ztkr7ttldm3zxw9jhcxya9444y0znn6qhc8qs8czq39x9f7e6d83xs5sk06zk65g00n0vedz39c572nuu7q4u3k5xnrcd52z3rygycym4wuqnnhx8xeyj6c8am7tmr38uzc400hyz5q92xtp3aualuz0ec40qhuw8ur4fy36pq23e9udw22ampdm8slvue5dg96m09zk3vhzhykhatc5qu2ps3sapzfmv6qt9v2u7fwaw2gktpvxvuaclpy0dqjck0mhuysmexqpsq899xz

  - &tpm-cray age1tag1qd5s6fcv5upezjgzv4y39t0kfg0tgalwdfmf3elnccu5u87ctzgmxgmt756
  - &tpm-naitoh age1tag1qwdf600uvtxjw58z48lgkg2txky68jhnlrlr0tjdrkl80gqaume6ynnn57f

  - &mach age1se1qwrp2meyq50afmrydcq7ejfwh9hj6zxfwg5wmgg5q5eudavd090v7urw3d5
  - &woz age174yq43fu75xyuf5t92yeekejl6fx84zewy45wqzy538g2qx29clq3gfn3w

creation_rules:
  - path_regex: 'cray/.*$'
    key_groups:
    - age:
      - *sk-main
      - *sk-backup
      - *tpm-cray
  - path_regex: 'naitoh/.*$'
    key_groups:
    - age:
      - *sk-main
      - *sk-backup
      - *tpm-naitoh
  - path_regex: 'mach/.*$'
    key_groups:
    - age:
      - *sk-main
      - *sk-backup
      - *mach
  - path_regex: 'woz/.*$'
    key_groups:
    - age:
      - *sk-main
      - *sk-backup
      - *woz
  - path_regex: '.*$'
    key_groups:
    - age:
      - *sk-main
      - *sk-backup
      - *tpm-cray
      - *tpm-naitoh
      - *mach
      - *woz
