uni_email: ENC[AES256_GCM,data:tWJawUqBZ+hboaahIJGIo3kcGp2Yc4wXXFDyx/CLLQ==,iv:e48bxt8wgJRCZ+joYNaYXxRsFnPRxYqX66KN7mj2vcs=,tag:dDOhPj6efwK9dbIkUysJVg==,type:str]
full_name: ENC[AES256_GCM,data:STc8fS46fT1N0w+yGzlHIg==,iv:VXltx/pPwujfK6YaSjUZ2lRsk/jVUk5hHIHilLqDwlw=,tag:9kirD9oszDT0rl3Sss0MIg==,type:str]
aerc_posteo_pw: ENC[AES256_GCM,data:KvMkWww0Vuyo2z1z4cJYnEgChJw/KeBNUWPs9hJrUDsd8GbmgDquiBbdoMaGHjelSepveOScC1in38SITzpL5XEO/oe4nRoKW88Qh655UnXPPMuR/EGsPBPKvf88QFlMZBK2IPYHvMg0fz3/ql7TLxKvDbmGf+mmMWFOQ/ZVi+Mge3FEUsID0NDfXSrmtpwbf/pA5t40xfwMjLwwtxim0asSI/SSCGdtrlOarOHTdbVC1Nf2SfsU9u/tMDIBVG/zCPzRyr4zaJzfS9LOFjCKpLMnXJaUZCsAOpEnXA7QCrDBzgKIgH9/mwHHDutW3PM4gQ44H1eimo9DjtW/HtDqq+hl10/UeFYQSVXUN2Yp2cvouCHf0SaHq86rI4s9yEtvqZ0EbSk+snYDP+vTA392ijbG3W9sk8JzdvIH2Ce12S0nYN0DYy92X0782VG9IYN4pZcH9VpNuoZLnli/yLOqrN0BYPCN/TCBAK6jJVAYz/VRz5KldUM0eLCVBGfpiLkUn/i7f89UZ0vtiAT5QoaYjvqUfU9vWLcO6RuUIJ1ib7xriGQhKdeW+I/ktrqoui29yVo+soXOr2pANlqY8fYIS5Fp/euc8laj5/31mcNggCIkyFW0mSGpjVMBrSpHmzQnOZx8IA9jT1bCLnmI5qF6BcS6mHpP+xs=,iv:5V+HKRW0i/dOh2Z/Sw+H4X7RMHkV3HlguglEw/czx2M=,tag:V75s7wHJMEEsieevXOi53Q==,type:str]
coordinates: ENC[AES256_GCM,data:aa+OX+RydXTG0RAv79u2,iv:wEV5BjWP4EAaDxL/mmw0DeG7ZshRXqn1a2tz804srEc=,tag:wrBKS3RaFfJhP1VvDIk6WA==,type:str]
server_vpn_endpoint: ENC[AES256_GCM,data:qXk/uAUtPQFJYcI=,iv:SzIVmuNyJnx/9yvBlCzbXJfJwZjHqPMC8oZ/kepn6VU=,tag:CjjtDakL0NF6F8TEe0uF+A==,type:str]
home_ssid: ENC[AES256_GCM,data:A4JvRuxRv/X3DUhzRMU=,iv:Gg1UTqqUywxDFCqvgA7YDWCVkUpqbEm/SgoLjPV6LUc=,tag:wTKcMkCZAcnxtK6zsYSdAw==,type:str]
user_pw: ENC[AES256_GCM,data:xVJ6O2o/+ltbyOfjTPyjqx7NmqB9R5B/4Jb0EENhdkHC6GiFmNppExtRwDaXH82ZayQAKCaEkJ+gdpiMqQ7Th1Z5661I/Eh6RQ==,iv:1xTltuY5j0r+sR+sHXGQYuaPXq5QC7XHrPAiLShfxLQ=,tag:PRNhp6cO8HkHv7PZGRIMaQ==,type:str]
root_pw: ENC[AES256_GCM,data:XlUI8yRtVw3PTy4f0tTVW0VlDwo+46oxezQbP4fTDOZ5ylJEuoO2MzAaGaPgdCJuQCBgF8fGzxbqcokn3BpKayVNYXDZUk+xXg==,iv:2J5P/7Gl4Qbj04/Eh0AkbaD/QTvTesmBl2U1GAJUxzs=,tag:n+u/GFSzGsp9dkcX0pE04A==,type:str]
syncthing_pw: ENC[AES256_GCM,data:Ln4F4UTxr0scoZzoGrv9uk500g==,iv:sCL3SLKEARzA9YdRW8VVPmuIToSpSkQkUwY7v2s/cU4=,tag:jDnDQHOogKG1FXeLpI1ndA==,type:str]
attic_access_token: ENC[AES256_GCM,data:ZlR+620/olgj1/Nt60FAfTCVRGUFUFWXpQ465O4UTxCuRFjYVZ6z8j2zQM3Tb177hgmcLI5vG75g9JLf5wuueZK7aIh/ncTkBfZefBLPSVCU1W9wszkG6Fvm8nnnxAIkhXYQ5pCJZgzhOR818HJzdLPZIKTzziVI0tyhqi0mafaIA9Wrpc5I9Glga/Y2MLG/jqaEI4pipjDDPjqh4zF+UBcIFwevog6uFEukPex4m4IFFTyWej1Q6cHf00Cozy4RTgAZaEjEflVab7FBwDEVTlg0SreZEnlByKoRmJeu4bOV/Gm9vgmcIddtAiPL2XPR4O5PX8jRpUhqFVQfJpz4mkNsT4ywhBgDhVKZkSjnjLTD2ZO32mx5FdzaguHtH4HQgTIBwIiOqEMG5PsdsOkAswxluNShFlSVnzTnrgIuOqiTVmtyO41TSUW+uDdbAklvuSJNZ9NACdmTve/8tNMx6KXd76ZUQ9M/MiTAyOVIE0Y/jQ0bKy9oUERBxiBdRca430pp1ztn5IVRgms9cXOW3B4cEZle5U5joLEetWDCHFxeF7B8zfYFfeF8L9LOsN0KDAI0G/3G6TnBrrlmQFTSTzvf7eLW48XEPsczuqJTOGh3m1giQOiQ85mBnyz3wfPugxV14ga0hPZKhnPvsLoLY8XyTPTxQcEr2AJ2fwYdbq47zAFAFUgJYSiQifIqzX5ctv1BEQb57s7ydoe7VLDYcfMOQOtKIpt3efWs+vrhpcDVQ4hlCJusFHWSOMt01RM8XddLGCbF0mj61ZsQpMnNYjv35jzjeg1qrMCyuTFRim/nTh34di/fuTSvi7QPxOw9qTcw8XBjVM7sFxzo3s+3lkJ/zSxbX1xrRfpEA7xgH0ookFo69H6RkCdMJTBJn+reqzAlViYkEFS0OF/aHkof4bmd08DVfGDzvtBYtzf0lb3BRRFmBPzKrgCn0w0iq84+aefZSMGZv0XaSQ0WQDOoof06pk6GvSnW+y7A1v/WiLqkFbvbNNpouC/ytoHLuavGHl0IaRuhcmNY+rZM2xKTNRJZSYntqSxS9YAviFeL0BA+ot63hogke4BuiufAXbx3k3pihNw3Vo9x5RTEHYJYXm4/NAqrL+4qohtrBoWKn4DMrv/VaLUoW75ratqrQitDtZUOb+Dg7tc=,iv:bGd5MBWcGcspyhGd6j4E8PZCQl1fyFCSY41XV8XYOF4=,tag:bBhGEonAPAQxGOzb7BT1/Q==,type:str]
calendar_pw: ENC[AES256_GCM,data:dsvgvcEEWd1XzbrTOL3Sf1Ti51I=,iv:n/gNK0XLWWIMXO3sNiGqC2wc5L8txIQqZimY3flKHIQ=,tag:kswSwMfMg35kdeHzCXZZsg==,type:str]
github_token: ENC[AES256_GCM,data:Zg6HXmrI/mFLZkHQazgiwDrYk+0NJAVqLL6VvgwERNSJIL80KcmuWA==,iv:KXFBHi7QCEPj+6mqHF1txisdLHkAYUJ5CMA/MDQsrDM=,tag:AeJ8fG2JXC5xBf8pbPurTQ==,type:str]
airvpn:
    pk: ENC[AES256_GCM,data:BH5D8PZnKV6HIhbZdyu2Wuv0gDjPIHFEn2+GuF3UngINTfTjo/QTja397A4=,iv:EgDaI6+3AL8I/DgqI8jr58i8VvuAorgVZ7UyW6ABo+o=,tag:Uhoo61JQhkMFZ3lJ4RexUw==,type:str]
    psk: ENC[AES256_GCM,data:Jr+9t/65FllLlAoCStBvJQR2wldSokX5+1pRKjsDpyRCXzLwnYp4QUoXJos=,iv:SlwvLt/FDhxf/8x97VNnRclsGz+n12uKXruTQT+B0lw=,tag:+iZUAUxekkkaTNZCak/mcQ==,type:str]
    sk: ENC[AES256_GCM,data:RPd4waI28P2N7EM0WRQR8cOSTqHzd4eHFM1oL1T3gUaXuoRQE9GzGXIEwzc=,iv:Af45O4/8gdmpc4ExrnGFjLT/Z3g+WCccR0pWNBTxEJ8=,tag:x9sJh08ohy4LNQmnglnuOQ==,type:str]
shannon:
    vpn:
        psk: ENC[AES256_GCM,data:mzsmx02K/79lLkbAOQLpWUo2DWx9FK1MitMLRyHAHAq6KhwBvVVFFXNejFo=,iv:hbqUOA7HymgorHsZdhkVnC+y1Yc6tVXFJtEF7tKbRQs=,tag:QfTjNGYFTJMA2+V+SMLuBQ==,type:str]
yoshino:
    vpn:
        psk: ENC[AES256_GCM,data:VANlVITsFcl/RcydhweR7t6vB6p5jiMP1NJn7/kT48sulyk6C4n5utC3C2o=,iv:FVeY3pBIRBUnXA8l9/BBKagX5jun6NpZ0ydXDjOmdfI=,tag:m5zMX2R2mXtZgmkmwXghtg==,type:str]
lamarr:
    vpn:
        psk: ENC[AES256_GCM,data:JgCv9BDJZLnCn4E/OZqDI1wps1Mo+NT2j8w9n6v3QogiaynO93oFSvRPO2o=,iv:KSDze9igkQt2qFCgt5bSNzzchZ0W+y6LT+2CdKJ7KYo=,tag:h3beFVbsDTik1770ryrY5g==,type:str]
cray:
    vpn:
        psk: ENC[AES256_GCM,data:6rVacTDm7TpoxQHFHCPDUxWFDis87Ggn0cBqzqRufYwvip2U1vQb24JgOGc=,iv:zXwapLDlzdzElAhHaWstknY+dp+M3JS9YwdabFpbms8=,tag:NNb2xW/AWwfDCprBKZilew==,type:str]
mach:
    vpn:
        psk: ENC[AES256_GCM,data:eIBR/DTNpPDR7Oe+A2WPPKVIJtmqZZe4MqNtIGjY/zBTAeEc0VxDG/gm4Z4=,iv:G6+Ho3wSi/i09AZ+fT8D/ZHYA3wKwB0MgfmUb5tO3Ik=,tag:8DFJdJf2wS+GDSb01B234A==,type:str]
naitoh:
    vpn:
        psk: ENC[AES256_GCM,data:cJ1Ip4Wgis0oKAR5hdvZUGq337RWiY3utnDLB9OIqJ/0redSX22XoXzmAoI=,iv:5WHSn9jSPC68VGvrueYLz61HgHaFeEHh9Xko6BGg7XE=,tag:o3yqOU94ACM3BJWiS66Wsw==,type:str]
woz:
    vpn:
        psk: ENC[AES256_GCM,data:dVgLo9G5zIvTuTF7ytLzsKRYVnzgT/dyyUGHcjNI+MD3S3NJwSNDW39iLRk=,iv:N+NDM/495cm72NXpKzob6it9sGbTO2aidYgnQlPnuBg=,tag:U36DqyV7tMSzdxYd9sYjbw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZmVIRTQ3NVpWaTRSQ3N1
            MjRtU2ZMWjFMaTFDM09uWHFxRFNLRlZvVGprCjRJOG1IR0ZHZFg2YnR3YmFOajJr
            RWxHcnNDU0Nzam1SQyt5d2pYd2EzdE0KLS0tICt4OU5UNlNERmtidjlmNmJucm50
            UzBnLytKUHh5N1pxRWxrZy9TMEo2NXMKJO04e0fmFWD/e6QUDI7T3hYixOTg3nMY
            qObedetaa18VIR4oENpTUDSo6OOp3lF2C0rouZFs2c7KGl9nOnaldw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1zmpz7zl6hjrqarz4w5lsnkrqw66e63np08pdt8c5rrdh70etlqwq03ksp7
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBMSHBFUmlNZjU4U3RSN3dz
            NWZSanVBeWkyMmx4cXlSQmhFZDNUMFBjQXlFCklXbzAzZFpTOE4vTzZuTFhQWGtG
            OGoySTNDS0U5bTNwWEdmSjFRa1J2aHcKLS0tIG1FbVN2KzNUa3pJQVlNKzNXbk1a
            ZkdJa2VKdFl0S3JKSk04b0VRUmlrNWcKUvnQATD6ok9Nn4tmqcYeeX9P1qVdb1t2
            QPZVDcr2jStSPVjeA8LFTM847Wm/ASJDhCBJs3myvUPNrQTnpv+yKQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1n4q00k9aas6g7eexc7spv32j02m3wez2gcnucre0tx76swazv36q8qchnq
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgMnYyNFF3IEJFRUJXUWI4
            cWlBZHZFbEpwYjhiQUNmNCtjVW5VaXlaTjBwOTREOTVBMytkQ2lNMDBLaCtOOThy
            TEhCcEJIbzZrOUV5bGc0b3U3dVBibzM1ekNCNHlxSQo4MFZrVlBIY29lVkN0Ym1a
            cmFHWDUwWnlUVVlDcnl0dmFLaG5KNndrbTFnCi0tLSBlaEh2STQ3aUt5aForTTQr
            M1Bza2pZaXp3L2Q1Qit4VzBBb3ZuUXhCRE1rCgvYpgc0jU9M3ePz8Nr48Rlte+J9
            uWUslzDtw1o/oIhzZS24MkL5ilgdexZBv9Q8tirAFJfS5bw9mWmw02l4Idg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1qd5s6fcv5upezjgzv4y39t0kfg0tgalwdfmf3elnccu5u87ctzgmxgmt756
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHAyNTZ0YWcgNy9mamZBIEJEODZKalRD
            SVJFSkV5WjlSRkJrb2g3SHJ6L1NUbWRyNExRSGNqa0ZZSStzd2hCMnZxRVBHVWNQ
            ZVR4Qlh3dndXeU5HVHUreGpEQ0xWamRRejZMOTZ6VQpPdFBiWHpUVkF1VUdZY1hs
            bXh2V3dWVVFybThtc1dRMFZxWGFSN1lvUzBvCi0tLSBZaWIrZnVjOGNVOWxuMll3
            VkZOTkZoQnNTZUg0WDBIOElLTnBJaVNmZVBzCjhPVicV+C4MPyr0/kzCtZCZamSt
            +QAHCaPFQfMiitG3lvsioj3istYgt5vBolsMoRFlFs8f9geutvD9aDjmPaU=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1tag1qwdf600uvtxjw58z48lgkg2txky68jhnlrlr0tjdrkl80gqaume6ynnn57f
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHBpdi1wMjU2IE8zUXdoUSBBeWQvWm1P
            V2hKa3AwSmhOcWxaajBvMTN0c3p4S3VKazlWdkp1K2lMOTZadAp1ZHBaanZiMkJB
            VStVdStHMEFKbUNrZEUrTjVTbDVlMGd5b3pEMkRoMGdvCi0tLSBwZkpMb3NXN3E0
            cUR5dlhXcjN3cUhYTFc2Tk84aHZkVU5TbDh0YXNxVGpRCjagVlfcyoZhCI4KUN8s
            bjRAUgfNJLgTeYa4fB9RS7g5MDByWwUAQkGGQXCleVV67UovWXXKyiYBd8+bZdBz
            Qjg=
            -----END AGE ENCRYPTED FILE-----
          recipient: age1se1qwrp2meyq50afmrydcq7ejfwh9hj6zxfwg5wmgg5q5eudavd090v7urw3d5
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5dXM4dUR3SUdjTW02dUZE
            WmZRanVVcVZnRjk2Yi9TQWhVTkZMUS9DU3hnCjdJa0RncUFkWXNUK1NseWpZeVZ4
            TjdjcDZFZnNzR1VqM0RmS1R5cXNMSTQKLS0tIG1NUzd2RWhac0VEclU5aDF3YjJ6
            NnIwNEk0MzBpVWhNYUNMZ2p1dUMycmcKtNwiAekcDWBgxchr1C3pjlDxCQiWc1hT
            wVaDU1xK/99OyMKle/xAZ+P2elAVb5GThPF6OKWevfV7bsV1wigTCA==
            -----END AGE ENCRYPTED FILE-----
          recipient: age174yq43fu75xyuf5t92yeekejl6fx84zewy45wqzy538g2qx29clq3gfn3w
    lastmodified: "2026-08-18T11:42:07Z"
    mac: ENC[AES256_GCM,data:9zqlJLhVGRL2tAL78OpxSIzlYYY3Vcoje/gf4hCsE2jqvAKMHNzQdsSpLvsWLKZWvLVMm/FbhfDqupCUn6mNXLaZTax2yYqaA9RNR3GAI8R+c0E/xJJys9FNtf+A1CyALsCcN2d8xTNl523wqpf1Ri26wqLI2iXj7nTo2Ycp6wU=,iv:EIy1tYKASdXToW87PCOLNmZvZJl1WqpQQlaOIe1pG9E=,tag:Bb7mcBU/vitpRxdO/+tz4Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.1
